export const departamentos = [
  { nombre: 'Antioquia', codigo: '05' },
  { nombre: 'Atlántico', codigo: '08' },
  { nombre: 'Bogotá, D.C.', codigo: '11' },
  { nombre: 'Bolívar', codigo: '13' },
  { nombre: 'Boyacá', codigo: '15' },
  { nombre: 'Caldas', codigo: '17' },
  { nombre: 'Caquetá', codigo: '18' },
  { nombre: 'Cauca', codigo: '19' },
  { nombre: 'Cesar', codigo: '20' },
  { nombre: 'Córdoba', codigo: '23' },
  { nombre: 'Cundinamarca', codigo: '25' },
  { nombre: 'Chocó', codigo: '27' },
  { nombre: 'Huila', codigo: '41' },
  { nombre: 'La Guajira', codigo: '44' },
  { nombre: 'Magdalena', codigo: '47' },
  { nombre: 'Meta', codigo: '50' },
  { nombre: 'Nariño', codigo: '52' },
  { nombre: 'Norte de Santander', codigo: '54' },
  { nombre: 'Quindío', codigo: '63' },
  { nombre: 'Risaralda', codigo: '66' },
  { nombre: 'Santander', codigo: '68' },
  { nombre: 'Sucre', codigo: '70' },
  { nombre: 'Tolima', codigo: '73' },
  { nombre: 'Valle del Cauca', codigo: '76' },
  { nombre: 'Arauca', codigo: '81' },
  { nombre: 'Casanare', codigo: '85' },
  { nombre: 'Putumayo', codigo: '86' },
  { nombre: 'Archipiélago de San Andrés, Providiencia y Santa Catalina', codigo: '88' },
  { nombre: 'Amazonas', codigo: '91' },
  { nombre: 'Guainía', codigo: '94' },
  { nombre: 'Guaviare', codigo: '95' },
  { nombre: 'Vaupés', codigo: '97' },
  { nombre: 'Vichada', codigo: '99' },
];

export const municipios = [
  { nombre: 'Leticia (Amazonas)', codigo: '91001' },
  { nombre: 'El Encanto (Amazonas)', codigo: '91263' },
  { nombre: 'La Chorrera (Amazonas)', codigo: '91405' },
  { nombre: 'La Pedrera (Amazonas)', codigo: '91407' },
  { nombre: 'La Victoria (Amazonas)', codigo: '91430' },
  { nombre: 'Mirití - Paraná (Amazonas)', codigo: '91460' },
  { nombre: 'Puerto Alegría (Amazonas)', codigo: '91530' },
  { nombre: 'Puerto Arica (Amazonas)', codigo: '91536' },
  { nombre: 'Puerto Nariño (Amazonas)', codigo: '91540' },
  { nombre: 'Puerto Santander (Amazonas)', codigo: '91669' },
  { nombre: 'Tarapacá (Amazonas)', codigo: '91798' },
  { nombre: 'Medellín (Antioquia)', codigo: '05001' },
  { nombre: 'Abejorral (Antioquia)', codigo: '05002' },
  { nombre: 'Abriaquí (Antioquia)', codigo: '05004' },
  { nombre: 'Alejandría (Antioquia)', codigo: '05021' },
  { nombre: 'Amagá (Antioquia)', codigo: '05030' },
  { nombre: 'Amalfi (Antioquia)', codigo: '05031' },
  { nombre: 'Andes (Antioquia)', codigo: '05034' },
  { nombre: 'Angelópolis (Antioquia)', codigo: '05036' },
  { nombre: 'Angostura (Antioquia)', codigo: '05038' },
  { nombre: 'Anorí (Antioquia)', codigo: '05040' },
  { nombre: 'Santa Fé de Antioquia (Antioquia)', codigo: '05042' },
  { nombre: 'Anzá (Antioquia)', codigo: '05044' },
  { nombre: 'Apartadó (Antioquia)', codigo: '05045' },
  { nombre: 'Arboletes (Antioquia)', codigo: '05051' },
  { nombre: 'Argelia (Antioquia)', codigo: '05055' },
  { nombre: 'Armenia (Antioquia)', codigo: '05059' },
  { nombre: 'Barbosa (Antioquia)', codigo: '05079' },
  { nombre: 'Belmira (Antioquia)', codigo: '05086' },
  { nombre: 'Bello (Antioquia)', codigo: '05088' },
  { nombre: 'Betania (Antioquia)', codigo: '05091' },
  { nombre: 'Betulia (Antioquia)', codigo: '05093' },
  { nombre: 'Ciudad Bolívar (Antioquia)', codigo: '05101' },
  { nombre: 'Briceño (Antioquia)', codigo: '05107' },
  { nombre: 'Buriticá (Antioquia)', codigo: '05113' },
  { nombre: 'Cáceres (Antioquia)', codigo: '05120' },
  { nombre: 'Caicedo (Antioquia)', codigo: '05125' },
  { nombre: 'Caldas (Antioquia)', codigo: '05129' },
  { nombre: 'Campamento (Antioquia)', codigo: '05134' },
  { nombre: 'Cañasgordas (Antioquia)', codigo: '05138' },
  { nombre: 'Caracolí (Antioquia)', codigo: '05142' },
  { nombre: 'Caramanta (Antioquia)', codigo: '05145' },
  { nombre: 'Carepa (Antioquia)', codigo: '05147' },
  { nombre: 'El Carmen de Viboral (Antioquia)', codigo: '05148' },
  { nombre: 'Carolina (Antioquia)', codigo: '05150' },
  { nombre: 'Caucasia (Antioquia)', codigo: '05154' },
  { nombre: 'Chigorodó (Antioquia)', codigo: '05172' },
  { nombre: 'Cisneros (Antioquia)', codigo: '05190' },
  { nombre: 'Cocorná (Antioquia)', codigo: '05197' },
  { nombre: 'Concepción (Antioquia)', codigo: '05206' },
  { nombre: 'Concordia (Antioquia)', codigo: '05209' },
  { nombre: 'Copacabana (Antioquia)', codigo: '05212' },
  { nombre: 'Dabeiba (Antioquia)', codigo: '05234' },
  { nombre: 'Donmatías (Antioquia)', codigo: '05237' },
  { nombre: 'Ebéjico (Antioquia)', codigo: '05240' },
  { nombre: 'El Bagre (Antioquia)', codigo: '05250' },
  { nombre: 'Entrerríos (Antioquia)', codigo: '05264' },
  { nombre: 'Envigado (Antioquia)', codigo: '05266' },
  { nombre: 'Fredonia (Antioquia)', codigo: '05282' },
  { nombre: 'Frontino (Antioquia)', codigo: '05284' },
  { nombre: 'Giraldo (Antioquia)', codigo: '05306' },
  { nombre: 'Girardota (Antioquia)', codigo: '05308' },
  { nombre: 'Gómez Plata (Antioquia)', codigo: '05310' },
  { nombre: 'Granada (Antioquia)', codigo: '05313' },
  { nombre: 'Guadalupe (Antioquia)', codigo: '05315' },
  { nombre: 'Guarne (Antioquia)', codigo: '05318' },
  { nombre: 'Guatapé (Antioquia)', codigo: '05321' },
  { nombre: 'Heliconia (Antioquia)', codigo: '05347' },
  { nombre: 'Hispania (Antioquia)', codigo: '05353' },
  { nombre: 'Itagüí (Antioquia)', codigo: '05360' },
  { nombre: 'Ituango (Antioquia)', codigo: '05361' },
  { nombre: 'Jardín (Antioquia)', codigo: '05364' },
  { nombre: 'Jericó (Antioquia)', codigo: '05368' },
  { nombre: 'La Ceja (Antioquia)', codigo: '05376' },
  { nombre: 'La Estrella (Antioquia)', codigo: '05380' },
  { nombre: 'La Pintada (Antioquia)', codigo: '05390' },
  { nombre: 'La Unión (Antioquia)', codigo: '05400' },
  { nombre: 'Liborina (Antioquia)', codigo: '05411' },
  { nombre: 'Maceo (Antioquia)', codigo: '05425' },
  { nombre: 'Marinilla (Antioquia)', codigo: '05440' },
  { nombre: 'Montebello (Antioquia)', codigo: '05467' },
  { nombre: 'Murindó (Antioquia)', codigo: '05475' },
  { nombre: 'Mutatá (Antioquia)', codigo: '05480' },
  { nombre: 'Nariño (Antioquia)', codigo: '05483' },
  { nombre: 'Necoclí (Antioquia)', codigo: '05490' },
  { nombre: 'Nechí (Antioquia)', codigo: '05495' },
  { nombre: 'Olaya (Antioquia)', codigo: '05501' },
  { nombre: 'Peñol (Antioquia)', codigo: '05541' },
  { nombre: 'Peque (Antioquia)', codigo: '05543' },
  { nombre: 'Pueblorrico (Antioquia)', codigo: '05576' },
  { nombre: 'Puerto Berrío (Antioquia)', codigo: '05579' },
  { nombre: 'Puerto Nare (Antioquia)', codigo: '05585' },
  { nombre: 'Puerto Triunfo (Antioquia)', codigo: '05591' },
  { nombre: 'Remedios (Antioquia)', codigo: '05604' },
  { nombre: 'Retiro (Antioquia)', codigo: '05607' },
  { nombre: 'Rionegro (Antioquia)', codigo: '05615' },
  { nombre: 'Sabanalarga (Antioquia)', codigo: '05628' },
  { nombre: 'Sabaneta (Antioquia)', codigo: '05631' },
  { nombre: 'Salgar (Antioquia)', codigo: '05642' },
  { nombre: 'San Andrés de Cuerquía (Antioquia)', codigo: '05647' },
  { nombre: 'San Carlos (Antioquia)', codigo: '05649' },
  { nombre: 'San Francisco (Antioquia)', codigo: '05652' },
  { nombre: 'San Jerónimo (Antioquia)', codigo: '05656' },
  { nombre: 'San José de la Montaña (Antioquia)', codigo: '05658' },
  { nombre: 'San Juan de Urabá (Antioquia)', codigo: '05659' },
  { nombre: 'San Luis (Antioquia)', codigo: '05660' },
  { nombre: 'San Pedro de Los Milagros (Antioquia)', codigo: '05664' },
  { nombre: 'San Pedro de Urabá (Antioquia)', codigo: '05665' },
  { nombre: 'San Rafael (Antioquia)', codigo: '05667' },
  { nombre: 'San Roque (Antioquia)', codigo: '05670' },
  { nombre: 'San Vicente Ferrer (Antioquia)', codigo: '05674' },
  { nombre: 'Santa Bárbara (Antioquia)', codigo: '05679' },
  { nombre: 'Santa Rosa de Osos (Antioquia)', codigo: '05686' },
  { nombre: 'Santo Domingo (Antioquia)', codigo: '05690' },
  { nombre: 'El Santuario (Antioquia)', codigo: '05697' },
  { nombre: 'Segovia (Antioquia)', codigo: '05736' },
  { nombre: 'Sonsón (Antioquia)', codigo: '05756' },
  { nombre: 'Sopetrán (Antioquia)', codigo: '05761' },
  { nombre: 'Támesis (Antioquia)', codigo: '05789' },
  { nombre: 'Tarazá (Antioquia)', codigo: '05790' },
  { nombre: 'Tarso (Antioquia)', codigo: '05792' },
  { nombre: 'Titiribí (Antioquia)', codigo: '05809' },
  { nombre: 'Toledo (Antioquia)', codigo: '05819' },
  { nombre: 'Turbo (Antioquia)', codigo: '05837' },
  { nombre: 'Uramita (Antioquia)', codigo: '05842' },
  { nombre: 'Urrao (Antioquia)', codigo: '05847' },
  { nombre: 'Valdivia (Antioquia)', codigo: '05854' },
  { nombre: 'Valparaíso (Antioquia)', codigo: '05856' },
  { nombre: 'Vegachí (Antioquia)', codigo: '05858' },
  { nombre: 'Venecia (Antioquia)', codigo: '05861' },
  { nombre: 'Vigía del Fuerte (Antioquia)', codigo: '05873' },
  { nombre: 'Yalí (Antioquia)', codigo: '05885' },
  { nombre: 'Yarumal (Antioquia)', codigo: '05887' },
  { nombre: 'Yolombó (Antioquia)', codigo: '05890' },
  { nombre: 'Yondó (Antioquia)', codigo: '05893' },
  { nombre: 'Zaragoza (Antioquia)', codigo: '05895' },
  { nombre: 'Arauca (Arauca)', codigo: '81001' },
  { nombre: 'Arauquita (Arauca)', codigo: '81065' },
  { nombre: 'Cravo Norte (Arauca)', codigo: '81220' },
  { nombre: 'Fortul (Arauca)', codigo: '81300' },
  { nombre: 'Puerto Rondón (Arauca)', codigo: '81591' },
  { nombre: 'Saravena (Arauca)', codigo: '81736' },
  { nombre: 'Tame (Arauca)', codigo: '81794' },
  { nombre: 'San Andrés (Archipiélago de San Andrés, Providiencia y Santa Catalina)', codigo: '88001' },
  { nombre: 'Providencia (Archipiélago de San Andrés, Providiencia y Santa Catalina)', codigo: '88564' },
  { nombre: 'Barranquilla (Atlántico)', codigo: '08001' },
  { nombre: 'Baranoa (Atlántico)', codigo: '08078' },
  { nombre: 'Campo de la Cruz (Atlántico)', codigo: '08137' },
  { nombre: 'Candelaria (Atlántico)', codigo: '08141' },
  { nombre: 'Galapa (Atlántico)', codigo: '08296' },
  { nombre: 'Juan de Acosta (Atlántico)', codigo: '08372' },
  { nombre: 'Luruaco (Atlántico)', codigo: '08421' },
  { nombre: 'Malambo (Atlántico)', codigo: '08433' },
  { nombre: 'Manatí (Atlántico)', codigo: '08436' },
  { nombre: 'Palmar de Varela (Atlántico)', codigo: '08520' },
  { nombre: 'Piojó (Atlántico)', codigo: '08549' },
  { nombre: 'Polonuevo (Atlántico)', codigo: '08558' },
  { nombre: 'Ponedera (Atlántico)', codigo: '08560' },
  { nombre: 'Puerto Colombia (Atlántico)', codigo: '08573' },
  { nombre: 'Repelón (Atlántico)', codigo: '08606' },
  { nombre: 'Sabanagrande (Atlántico)', codigo: '08634' },
  { nombre: 'Sabanalarga (Atlántico)', codigo: '08638' },
  { nombre: 'Santa Lucía (Atlántico)', codigo: '08675' },
  { nombre: 'Santo Tomás (Atlántico)', codigo: '08685' },
  { nombre: 'Soledad (Atlántico)', codigo: '08758' },
  { nombre: 'Suan (Atlántico)', codigo: '08770' },
  { nombre: 'Tubará (Atlántico)', codigo: '08832' },
  { nombre: 'Usiacurí (Atlántico)', codigo: '08849' },
  { nombre: 'Bogotá, D.C. (Bogotá, D.C.)', codigo: '11001' },
  { nombre: 'Cartagena de Indias (Bolívar)', codigo: '13001' },
  { nombre: 'Achí (Bolívar)', codigo: '13006' },
  { nombre: 'Altos del Rosario (Bolívar)', codigo: '13030' },
  { nombre: 'Arenal (Bolívar)', codigo: '13042' },
  { nombre: 'Arjona (Bolívar)', codigo: '13052' },
  { nombre: 'Arroyohondo (Bolívar)', codigo: '13062' },
  { nombre: 'Barranco de Loba (Bolívar)', codigo: '13074' },
  { nombre: 'Calamar (Bolívar)', codigo: '13140' },
  { nombre: 'Cantagallo (Bolívar)', codigo: '13160' },
  { nombre: 'Cicuco (Bolívar)', codigo: '13188' },
  { nombre: 'Córdoba (Bolívar)', codigo: '13212' },
  { nombre: 'Clemencia (Bolívar)', codigo: '13222' },
  { nombre: 'El Carmen de Bolívar (Bolívar)', codigo: '13244' },
  { nombre: 'El Guamo (Bolívar)', codigo: '13248' },
  { nombre: 'El Peñón (Bolívar)', codigo: '13268' },
  { nombre: 'Hatillo de Loba (Bolívar)', codigo: '13300' },
  { nombre: 'Magangué (Bolívar)', codigo: '13430' },
  { nombre: 'Mahates (Bolívar)', codigo: '13433' },
  { nombre: 'Margarita (Bolívar)', codigo: '13440' },
  { nombre: 'María la Baja (Bolívar)', codigo: '13442' },
  { nombre: 'Montecristo (Bolívar)', codigo: '13458' },
  { nombre: 'Santa Cruz de Mompox (Bolívar)', codigo: '13468' },
  { nombre: 'Morales (Bolívar)', codigo: '13473' },
  { nombre: 'Norosí (Bolívar)', codigo: '13490' },
  { nombre: 'Pinillos (Bolívar)', codigo: '13549' },
  { nombre: 'Regidor (Bolívar)', codigo: '13580' },
  { nombre: 'Río Viejo (Bolívar)', codigo: '13600' },
  { nombre: 'San Cristóbal (Bolívar)', codigo: '13620' },
  { nombre: 'San Estanislao (Bolívar)', codigo: '13647' },
  { nombre: 'San Fernando (Bolívar)', codigo: '13650' },
  { nombre: 'San Jacinto (Bolívar)', codigo: '13654' },
  { nombre: 'San Jacinto del Cauca (Bolívar)', codigo: '13655' },
  { nombre: 'San Juan Nepomuceno (Bolívar)', codigo: '13657' },
  { nombre: 'San Martín de Loba (Bolívar)', codigo: '13667' },
  { nombre: 'San Pablo (Bolívar)', codigo: '13670' },
  { nombre: 'Santa Catalina (Bolívar)', codigo: '13673' },
  { nombre: 'Santa Rosa (Bolívar)', codigo: '13683' },
  { nombre: 'Santa Rosa del Sur (Bolívar)', codigo: '13688' },
  { nombre: 'Simití (Bolívar)', codigo: '13744' },
  { nombre: 'Soplaviento (Bolívar)', codigo: '13760' },
  { nombre: 'Talaigua Nuevo (Bolívar)', codigo: '13780' },
  { nombre: 'Tiquisio (Bolívar)', codigo: '13810' },
  { nombre: 'Turbaco (Bolívar)', codigo: '13836' },
  { nombre: 'Turbaná (Bolívar)', codigo: '13838' },
  { nombre: 'Villanueva (Bolívar)', codigo: '13873' },
  { nombre: 'Zambrano (Bolívar)', codigo: '13894' },
  { nombre: 'Tunja (Boyacá)', codigo: '15001' },
  { nombre: 'Almeida (Boyacá)', codigo: '15022' },
  { nombre: 'Aquitania (Boyacá)', codigo: '15047' },
  { nombre: 'Arcabuco (Boyacá)', codigo: '15051' },
  { nombre: 'Belén (Boyacá)', codigo: '15087' },
  { nombre: 'Berbeo (Boyacá)', codigo: '15090' },
  { nombre: 'Betéitiva (Boyacá)', codigo: '15092' },
  { nombre: 'Boavita (Boyacá)', codigo: '15097' },
  { nombre: 'Boyacá (Boyacá)', codigo: '15104' },
  { nombre: 'Briceño (Boyacá)', codigo: '15106' },
  { nombre: 'Buenavista (Boyacá)', codigo: '15109' },
  { nombre: 'Busbanzá (Boyacá)', codigo: '15114' },
  { nombre: 'Caldas (Boyacá)', codigo: '15131' },
  { nombre: 'Campohermoso (Boyacá)', codigo: '15135' },
  { nombre: 'Cerinza (Boyacá)', codigo: '15162' },
  { nombre: 'Chinavita (Boyacá)', codigo: '15172' },
  { nombre: 'Chiquinquirá (Boyacá)', codigo: '15176' },
  { nombre: 'Chiscas (Boyacá)', codigo: '15180' },
  { nombre: 'Chita (Boyacá)', codigo: '15183' },
  { nombre: 'Chitaraque (Boyacá)', codigo: '15185' },
  { nombre: 'Chivatá (Boyacá)', codigo: '15187' },
  { nombre: 'Ciénega (Boyacá)', codigo: '15189' },
  { nombre: 'Cómbita (Boyacá)', codigo: '15204' },
  { nombre: 'Coper (Boyacá)', codigo: '15212' },
  { nombre: 'Corrales (Boyacá)', codigo: '15215' },
  { nombre: 'Covarachía (Boyacá)', codigo: '15218' },
  { nombre: 'Cubará (Boyacá)', codigo: '15223' },
  { nombre: 'Cucaita (Boyacá)', codigo: '15224' },
  { nombre: 'Cuítiva (Boyacá)', codigo: '15226' },
  { nombre: 'Chíquiza (Boyacá)', codigo: '15232' },
  { nombre: 'Chivor (Boyacá)', codigo: '15236' },
  { nombre: 'Duitama (Boyacá)', codigo: '15238' },
  { nombre: 'El Cocuy (Boyacá)', codigo: '15244' },
  { nombre: 'El Espino (Boyacá)', codigo: '15248' },
  { nombre: 'Firavitoba (Boyacá)', codigo: '15272' },
  { nombre: 'Floresta (Boyacá)', codigo: '15276' },
  { nombre: 'Gachantivá (Boyacá)', codigo: '15293' },
  { nombre: 'Gámeza (Boyacá)', codigo: '15296' },
  { nombre: 'Garagoa (Boyacá)', codigo: '15299' },
  { nombre: 'Guacamayas (Boyacá)', codigo: '15317' },
  { nombre: 'Guateque (Boyacá)', codigo: '15322' },
  { nombre: 'Guayatá (Boyacá)', codigo: '15325' },
  { nombre: 'Güicán de la Sierra (Boyacá)', codigo: '15332' },
  { nombre: 'Iza (Boyacá)', codigo: '15362' },
  { nombre: 'Jenesano (Boyacá)', codigo: '15367' },
  { nombre: 'Jericó (Boyacá)', codigo: '15368' },
  { nombre: 'Labranzagrande (Boyacá)', codigo: '15377' },
  { nombre: 'La Capilla (Boyacá)', codigo: '15380' },
  { nombre: 'La Victoria (Boyacá)', codigo: '15401' },
  { nombre: 'La Uvita (Boyacá)', codigo: '15403' },
  { nombre: 'Villa de Leyva (Boyacá)', codigo: '15407' },
  { nombre: 'Macanal (Boyacá)', codigo: '15425' },
  { nombre: 'Maripí (Boyacá)', codigo: '15442' },
  { nombre: 'Miraflores (Boyacá)', codigo: '15455' },
  { nombre: 'Mongua (Boyacá)', codigo: '15464' },
  { nombre: 'Monguí (Boyacá)', codigo: '15466' },
  { nombre: 'Moniquirá (Boyacá)', codigo: '15469' },
  { nombre: 'Motavita (Boyacá)', codigo: '15476' },
  { nombre: 'Muzo (Boyacá)', codigo: '15480' },
  { nombre: 'Nobsa (Boyacá)', codigo: '15491' },
  { nombre: 'Nuevo Colón (Boyacá)', codigo: '15494' },
  { nombre: 'Oicatá (Boyacá)', codigo: '15500' },
  { nombre: 'Otanche (Boyacá)', codigo: '15507' },
  { nombre: 'Pachavita (Boyacá)', codigo: '15511' },
  { nombre: 'Páez (Boyacá)', codigo: '15514' },
  { nombre: 'Paipa (Boyacá)', codigo: '15516' },
  { nombre: 'Pajarito (Boyacá)', codigo: '15518' },
  { nombre: 'Panqueba (Boyacá)', codigo: '15522' },
  { nombre: 'Pauna (Boyacá)', codigo: '15531' },
  { nombre: 'Paya (Boyacá)', codigo: '15533' },
  { nombre: 'Paz de Río (Boyacá)', codigo: '15537' },
  { nombre: 'Pesca (Boyacá)', codigo: '15542' },
  { nombre: 'Pisba (Boyacá)', codigo: '15550' },
  { nombre: 'Puerto Boyacá (Boyacá)', codigo: '15572' },
  { nombre: 'Quípama (Boyacá)', codigo: '15580' },
  { nombre: 'Ramiriquí (Boyacá)', codigo: '15599' },
  { nombre: 'Ráquira (Boyacá)', codigo: '15600' },
  { nombre: 'Rondón (Boyacá)', codigo: '15621' },
  { nombre: 'Saboyá (Boyacá)', codigo: '15632' },
  { nombre: 'Sáchica (Boyacá)', codigo: '15638' },
  { nombre: 'Samacá (Boyacá)', codigo: '15646' },
  { nombre: 'San Eduardo (Boyacá)', codigo: '15660' },
  { nombre: 'San José de Pare (Boyacá)', codigo: '15664' },
  { nombre: 'San Luis de Gaceno (Boyacá)', codigo: '15667' },
  { nombre: 'San Mateo (Boyacá)', codigo: '15673' },
  { nombre: 'San Miguel de Sema (Boyacá)', codigo: '15676' },
  { nombre: 'San Pablo de Borbur (Boyacá)', codigo: '15681' },
  { nombre: 'Santana (Boyacá)', codigo: '15686' },
  { nombre: 'Santa María (Boyacá)', codigo: '15690' },
  { nombre: 'Santa Rosa de Viterbo (Boyacá)', codigo: '15693' },
  { nombre: 'Santa Sofía (Boyacá)', codigo: '15696' },
  { nombre: 'Sativanorte (Boyacá)', codigo: '15720' },
  { nombre: 'Sativasur (Boyacá)', codigo: '15723' },
  { nombre: 'Siachoque (Boyacá)', codigo: '15740' },
  { nombre: 'Soatá (Boyacá)', codigo: '15753' },
  { nombre: 'Socotá (Boyacá)', codigo: '15755' },
  { nombre: 'Socha (Boyacá)', codigo: '15757' },
  { nombre: 'Sogamoso (Boyacá)', codigo: '15759' },
  { nombre: 'Somondoco (Boyacá)', codigo: '15761' },
  { nombre: 'Sora (Boyacá)', codigo: '15762' },
  { nombre: 'Sotaquirá (Boyacá)', codigo: '15763' },
  { nombre: 'Soracá (Boyacá)', codigo: '15764' },
  { nombre: 'Susacón (Boyacá)', codigo: '15774' },
  { nombre: 'Sutamarchán (Boyacá)', codigo: '15776' },
  { nombre: 'Sutatenza (Boyacá)', codigo: '15778' },
  { nombre: 'Tasco (Boyacá)', codigo: '15790' },
  { nombre: 'Tenza (Boyacá)', codigo: '15798' },
  { nombre: 'Tibaná (Boyacá)', codigo: '15804' },
  { nombre: 'Tibasosa (Boyacá)', codigo: '15806' },
  { nombre: 'Tinjacá (Boyacá)', codigo: '15808' },
  { nombre: 'Tipacoque (Boyacá)', codigo: '15810' },
  { nombre: 'Toca (Boyacá)', codigo: '15814' },
  { nombre: 'Togüí (Boyacá)', codigo: '15816' },
  { nombre: 'Tópaga (Boyacá)', codigo: '15820' },
  { nombre: 'Tota (Boyacá)', codigo: '15822' },
  { nombre: 'Tununguá (Boyacá)', codigo: '15832' },
  { nombre: 'Turmequé (Boyacá)', codigo: '15835' },
  { nombre: 'Tuta (Boyacá)', codigo: '15837' },
  { nombre: 'Tutazá (Boyacá)', codigo: '15839' },
  { nombre: 'Úmbita (Boyacá)', codigo: '15842' },
  { nombre: 'Ventaquemada (Boyacá)', codigo: '15861' },
  { nombre: 'Viracachá (Boyacá)', codigo: '15879' },
  { nombre: 'Zetaquira (Boyacá)', codigo: '15897' },
  { nombre: 'Manizales (Caldas)', codigo: '17001' },
  { nombre: 'Aguadas (Caldas)', codigo: '17013' },
  { nombre: 'Anserma (Caldas)', codigo: '17042' },
  { nombre: 'Aranzazu (Caldas)', codigo: '17050' },
  { nombre: 'Belalcázar (Caldas)', codigo: '17088' },
  { nombre: 'Chinchiná (Caldas)', codigo: '17174' },
  { nombre: 'Filadelfia (Caldas)', codigo: '17272' },
  { nombre: 'La Dorada (Caldas)', codigo: '17380' },
  { nombre: 'La Merced (Caldas)', codigo: '17388' },
  { nombre: 'Manzanares (Caldas)', codigo: '17433' },
  { nombre: 'Marmato (Caldas)', codigo: '17442' },
  { nombre: 'Marquetalia (Caldas)', codigo: '17444' },
  { nombre: 'Marulanda (Caldas)', codigo: '17446' },
  { nombre: 'Neira (Caldas)', codigo: '17486' },
  { nombre: 'Norcasia (Caldas)', codigo: '17495' },
  { nombre: 'Pácora (Caldas)', codigo: '17513' },
  { nombre: 'Palestina (Caldas)', codigo: '17524' },
  { nombre: 'Pensilvania (Caldas)', codigo: '17541' },
  { nombre: 'Riosucio (Caldas)', codigo: '17614' },
  { nombre: 'Risaralda (Caldas)', codigo: '17616' },
  { nombre: 'Salamina (Caldas)', codigo: '17653' },
  { nombre: 'Samaná (Caldas)', codigo: '17662' },
  { nombre: 'San José (Caldas)', codigo: '17665' },
  { nombre: 'Supía (Caldas)', codigo: '17777' },
  { nombre: 'Victoria (Caldas)', codigo: '17867' },
  { nombre: 'Villamaría (Caldas)', codigo: '17873' },
  { nombre: 'Viterbo (Caldas)', codigo: '17877' },
  { nombre: 'Florencia (Caquetá)', codigo: '18001' },
  { nombre: 'Albania (Caquetá)', codigo: '18029' },
  { nombre: 'Belén de los Andaquíes (Caquetá)', codigo: '18094' },
  { nombre: 'Cartagena del Chairá (Caquetá)', codigo: '18150' },
  { nombre: 'Curillo (Caquetá)', codigo: '18205' },
  { nombre: 'El Doncello (Caquetá)', codigo: '18247' },
  { nombre: 'El Paujíl (Caquetá)', codigo: '18256' },
  { nombre: 'La Montañita (Caquetá)', codigo: '18410' },
  { nombre: 'Milán (Caquetá)', codigo: '18460' },
  { nombre: 'Morelia (Caquetá)', codigo: '18479' },
  { nombre: 'Puerto Rico (Caquetá)', codigo: '18592' },
  { nombre: 'San José del Fragua (Caquetá)', codigo: '18610' },
  { nombre: 'San Vicente del Caguán (Caquetá)', codigo: '18753' },
  { nombre: 'Solano (Caquetá)', codigo: '18756' },
  { nombre: 'Solita (Caquetá)', codigo: '18785' },
  { nombre: 'Valparaíso (Caquetá)', codigo: '18860' },
  { nombre: 'Yopal (Casanare)', codigo: '85001' },
  { nombre: 'Aguazul (Casanare)', codigo: '85010' },
  { nombre: 'Chámeza (Casanare)', codigo: '85015' },
  { nombre: 'Hato Corozal (Casanare)', codigo: '85125' },
  { nombre: 'La Salina (Casanare)', codigo: '85136' },
  { nombre: 'Maní (Casanare)', codigo: '85139' },
  { nombre: 'Monterrey (Casanare)', codigo: '85162' },
  { nombre: 'Nunchía (Casanare)', codigo: '85225' },
  { nombre: 'Orocué (Casanare)', codigo: '85230' },
  { nombre: 'Paz de Ariporo (Casanare)', codigo: '85250' },
  { nombre: 'Pore (Casanare)', codigo: '85263' },
  { nombre: 'Recetor (Casanare)', codigo: '85279' },
  { nombre: 'Sabanalarga (Casanare)', codigo: '85300' },
  { nombre: 'Sácama (Casanare)', codigo: '85315' },
  { nombre: 'San Luis de Palenque (Casanare)', codigo: '85325' },
  { nombre: 'Támara (Casanare)', codigo: '85400' },
  { nombre: 'Tauramena (Casanare)', codigo: '85410' },
  { nombre: 'Trinidad (Casanare)', codigo: '85430' },
  { nombre: 'Villanueva (Casanare)', codigo: '85440' },
  { nombre: 'Popayán (Cauca)', codigo: '19001' },
  { nombre: 'Almaguer (Cauca)', codigo: '19022' },
  { nombre: 'Argelia (Cauca)', codigo: '19050' },
  { nombre: 'Balboa (Cauca)', codigo: '19075' },
  { nombre: 'Bolívar (Cauca)', codigo: '19100' },
  { nombre: 'Buenos Aires (Cauca)', codigo: '19110' },
  { nombre: 'Cajibío (Cauca)', codigo: '19130' },
  { nombre: 'Caldono (Cauca)', codigo: '19137' },
  { nombre: 'Caloto (Cauca)', codigo: '19142' },
  { nombre: 'Corinto (Cauca)', codigo: '19212' },
  { nombre: 'El Tambo (Cauca)', codigo: '19256' },
  { nombre: 'Florencia (Cauca)', codigo: '19290' },
  { nombre: 'Guachené (Cauca)', codigo: '19300' },
  { nombre: 'Guapi (Cauca)', codigo: '19318' },
  { nombre: 'Inzá (Cauca)', codigo: '19355' },
  { nombre: 'Jambaló (Cauca)', codigo: '19364' },
  { nombre: 'La Sierra (Cauca)', codigo: '19392' },
  { nombre: 'La Vega (Cauca)', codigo: '19397' },
  { nombre: 'López de Micay (Cauca)', codigo: '19418' },
  { nombre: 'Mercaderes (Cauca)', codigo: '19450' },
  { nombre: 'Miranda (Cauca)', codigo: '19455' },
  { nombre: 'Morales (Cauca)', codigo: '19473' },
  { nombre: 'Padilla (Cauca)', codigo: '19513' },
  { nombre: 'Páez (Cauca)', codigo: '19517' },
  { nombre: 'Patía (Cauca)', codigo: '19532' },
  { nombre: 'Piamonte (Cauca)', codigo: '19533' },
  { nombre: 'Piendamó - Tunía (Cauca)', codigo: '19548' },
  { nombre: 'Puerto Tejada (Cauca)', codigo: '19573' },
  { nombre: 'Puracé (Cauca)', codigo: '19585' },
  { nombre: 'Rosas (Cauca)', codigo: '19622' },
  { nombre: 'San Sebastián (Cauca)', codigo: '19693' },
  { nombre: 'Santander de Quilichao (Cauca)', codigo: '19698' },
  { nombre: 'Santa Rosa (Cauca)', codigo: '19701' },
  { nombre: 'Silvia (Cauca)', codigo: '19743' },
  { nombre: 'Sotará Paispamba (Cauca)', codigo: '19760' },
  { nombre: 'Suárez (Cauca)', codigo: '19780' },
  { nombre: 'Sucre (Cauca)', codigo: '19785' },
  { nombre: 'Timbío (Cauca)', codigo: '19807' },
  { nombre: 'Timbiquí (Cauca)', codigo: '19809' },
  { nombre: 'Toribío (Cauca)', codigo: '19821' },
  { nombre: 'Totoró (Cauca)', codigo: '19824' },
  { nombre: 'Villa Rica (Cauca)', codigo: '19845' },
  { nombre: 'Valledupar (Cesar)', codigo: '20001' },
  { nombre: 'Aguachica (Cesar)', codigo: '20011' },
  { nombre: 'Agustín Codazzi (Cesar)', codigo: '20013' },
  { nombre: 'Astrea (Cesar)', codigo: '20032' },
  { nombre: 'Becerril (Cesar)', codigo: '20045' },
  { nombre: 'Bosconia (Cesar)', codigo: '20060' },
  { nombre: 'Chimichagua (Cesar)', codigo: '20175' },
  { nombre: 'Chiriguaná (Cesar)', codigo: '20178' },
  { nombre: 'Curumaní (Cesar)', codigo: '20228' },
  { nombre: 'El Copey (Cesar)', codigo: '20238' },
  { nombre: 'El Paso (Cesar)', codigo: '20250' },
  { nombre: 'Gamarra (Cesar)', codigo: '20295' },
  { nombre: 'González (Cesar)', codigo: '20310' },
  { nombre: 'La Gloria (Cesar)', codigo: '20383' },
  { nombre: 'La Jagua de Ibirico (Cesar)', codigo: '20400' },
  { nombre: 'Manaure Balcón del Cesar (Cesar)', codigo: '20443' },
  { nombre: 'Pailitas (Cesar)', codigo: '20517' },
  { nombre: 'Pelaya (Cesar)', codigo: '20550' },
  { nombre: 'Pueblo Bello (Cesar)', codigo: '20570' },
  { nombre: 'Río de Oro (Cesar)', codigo: '20614' },
  { nombre: 'La Paz (Cesar)', codigo: '20621' },
  { nombre: 'San Alberto (Cesar)', codigo: '20710' },
  { nombre: 'San Diego (Cesar)', codigo: '20750' },
  { nombre: 'San Martín (Cesar)', codigo: '20770' },
  { nombre: 'Tamalameque (Cesar)', codigo: '20787' },
  { nombre: 'Quibdó (Chocó)', codigo: '27001' },
  { nombre: 'Acandí (Chocó)', codigo: '27006' },
  { nombre: 'Alto Baudó (Chocó)', codigo: '27025' },
  { nombre: 'Atrato (Chocó)', codigo: '27050' },
  { nombre: 'Bagadó (Chocó)', codigo: '27073' },
  { nombre: 'Bahía Solano (Chocó)', codigo: '27075' },
  { nombre: 'Bajo Baudó (Chocó)', codigo: '27077' },
  { nombre: 'Belén de Bajirá (Chocó)', codigo: '27086' },
  { nombre: 'Bojayá (Chocó)', codigo: '27099' },
  { nombre: 'El Cantón del San Pablo (Chocó)', codigo: '27135' },
  { nombre: 'Carmen del Darién (Chocó)', codigo: '27150' },
  { nombre: 'Cértegui (Chocó)', codigo: '27160' },
  { nombre: 'Condoto (Chocó)', codigo: '27205' },
  { nombre: 'El Carmen de Atrato (Chocó)', codigo: '27245' },
  { nombre: 'El Litoral del San Juan (Chocó)', codigo: '27250' },
  { nombre: 'Istmina (Chocó)', codigo: '27361' },
  { nombre: 'Juradó (Chocó)', codigo: '27372' },
  { nombre: 'Lloró (Chocó)', codigo: '27413' },
  { nombre: 'Medio Atrato (Chocó)', codigo: '27425' },
  { nombre: 'Medio Baudó (Chocó)', codigo: '27430' },
  { nombre: 'Medio San Juan (Chocó)', codigo: '27450' },
  { nombre: 'Nóvita (Chocó)', codigo: '27491' },
  { nombre: 'Nuquí (Chocó)', codigo: '27495' },
  { nombre: 'Río Iró (Chocó)', codigo: '27580' },
  { nombre: 'Río Quito (Chocó)', codigo: '27600' },
  { nombre: 'Riosucio (Chocó)', codigo: '27615' },
  { nombre: 'San José del Palmar (Chocó)', codigo: '27660' },
  { nombre: 'Sipí (Chocó)', codigo: '27745' },
  { nombre: 'Tadó (Chocó)', codigo: '27787' },
  { nombre: 'Unguía (Chocó)', codigo: '27800' },
  { nombre: 'Unión Panamericana (Chocó)', codigo: '27810' },
  { nombre: 'Agua de Dios (Cundinamarca)', codigo: '25001' },
  { nombre: 'Albán (Cundinamarca)', codigo: '25019' },
  { nombre: 'Anapoima (Cundinamarca)', codigo: '25035' },
  { nombre: 'Anolaima (Cundinamarca)', codigo: '25040' },
  { nombre: 'Arbeláez (Cundinamarca)', codigo: '25053' },
  { nombre: 'Beltrán (Cundinamarca)', codigo: '25086' },
  { nombre: 'Bituima (Cundinamarca)', codigo: '25095' },
  { nombre: 'Bojacá (Cundinamarca)', codigo: '25099' },
  { nombre: 'Cabrera (Cundinamarca)', codigo: '25120' },
  { nombre: 'Cachipay (Cundinamarca)', codigo: '25123' },
  { nombre: 'Cajicá (Cundinamarca)', codigo: '25126' },
  { nombre: 'Caparrapí (Cundinamarca)', codigo: '25148' },
  { nombre: 'Cáqueza (Cundinamarca)', codigo: '25151' },
  { nombre: 'Carmen de Carupa (Cundinamarca)', codigo: '25154' },
  { nombre: 'Chaguaní (Cundinamarca)', codigo: '25168' },
  { nombre: 'Chía (Cundinamarca)', codigo: '25175' },
  { nombre: 'Chipaque (Cundinamarca)', codigo: '25178' },
  { nombre: 'Choachí (Cundinamarca)', codigo: '25181' },
  { nombre: 'Chocontá (Cundinamarca)', codigo: '25183' },
  { nombre: 'Cogua (Cundinamarca)', codigo: '25200' },
  { nombre: 'Cota (Cundinamarca)', codigo: '25214' },
  { nombre: 'Cucunubá (Cundinamarca)', codigo: '25224' },
  { nombre: 'El Colegio (Cundinamarca)', codigo: '25245' },
  { nombre: 'El Peñón (Cundinamarca)', codigo: '25258' },
  { nombre: 'El Rosal (Cundinamarca)', codigo: '25260' },
  { nombre: 'Facatativá (Cundinamarca)', codigo: '25269' },
  { nombre: 'Fómeque (Cundinamarca)', codigo: '25279' },
  { nombre: 'Fosca (Cundinamarca)', codigo: '25281' },
  { nombre: 'Funza (Cundinamarca)', codigo: '25286' },
  { nombre: 'Fúquene (Cundinamarca)', codigo: '25288' },
  { nombre: 'Fusagasugá (Cundinamarca)', codigo: '25290' },
  { nombre: 'Gachalá (Cundinamarca)', codigo: '25293' },
  { nombre: 'Gachancipá (Cundinamarca)', codigo: '25295' },
  { nombre: 'Gachetá (Cundinamarca)', codigo: '25297' },
  { nombre: 'Gama (Cundinamarca)', codigo: '25299' },
  { nombre: 'Girardot (Cundinamarca)', codigo: '25307' },
  { nombre: 'Granada (Cundinamarca)', codigo: '25312' },
  { nombre: 'Guachetá (Cundinamarca)', codigo: '25317' },
  { nombre: 'Guaduas (Cundinamarca)', codigo: '25320' },
  { nombre: 'Guasca (Cundinamarca)', codigo: '25322' },
  { nombre: 'Guataquí (Cundinamarca)', codigo: '25324' },
  { nombre: 'Guatavita (Cundinamarca)', codigo: '25326' },
  { nombre: 'Guayabal de Síquima (Cundinamarca)', codigo: '25328' },
  { nombre: 'Guayabetal (Cundinamarca)', codigo: '25335' },
  { nombre: 'Gutiérrez (Cundinamarca)', codigo: '25339' },
  { nombre: 'Jerusalén (Cundinamarca)', codigo: '25368' },
  { nombre: 'Junín (Cundinamarca)', codigo: '25372' },
  { nombre: 'La Calera (Cundinamarca)', codigo: '25377' },
  { nombre: 'La Mesa (Cundinamarca)', codigo: '25386' },
  { nombre: 'La Palma (Cundinamarca)', codigo: '25394' },
  { nombre: 'La Peña (Cundinamarca)', codigo: '25398' },
  { nombre: 'La Vega (Cundinamarca)', codigo: '25402' },
  { nombre: 'Lenguazaque (Cundinamarca)', codigo: '25407' },
  { nombre: 'Machetá (Cundinamarca)', codigo: '25426' },
  { nombre: 'Madrid (Cundinamarca)', codigo: '25430' },
  { nombre: 'Manta (Cundinamarca)', codigo: '25436' },
  { nombre: 'Medina (Cundinamarca)', codigo: '25438' },
  { nombre: 'Mosquera (Cundinamarca)', codigo: '25473' },
  { nombre: 'Nariño (Cundinamarca)', codigo: '25483' },
  { nombre: 'Nemocón (Cundinamarca)', codigo: '25486' },
  { nombre: 'Nilo (Cundinamarca)', codigo: '25488' },
  { nombre: 'Nimaima (Cundinamarca)', codigo: '25489' },
  { nombre: 'Nocaima (Cundinamarca)', codigo: '25491' },
  { nombre: 'Venecia (Cundinamarca)', codigo: '25506' },
  { nombre: 'Pacho (Cundinamarca)', codigo: '25513' },
  { nombre: 'Paime (Cundinamarca)', codigo: '25518' },
  { nombre: 'Pandi (Cundinamarca)', codigo: '25524' },
  { nombre: 'Paratebueno (Cundinamarca)', codigo: '25530' },
  { nombre: 'Pasca (Cundinamarca)', codigo: '25535' },
  { nombre: 'Puerto Salgar (Cundinamarca)', codigo: '25572' },
  { nombre: 'Pulí (Cundinamarca)', codigo: '25580' },
  { nombre: 'Quebradanegra (Cundinamarca)', codigo: '25592' },
  { nombre: 'Quetame (Cundinamarca)', codigo: '25594' },
  { nombre: 'Quipile (Cundinamarca)', codigo: '25596' },
  { nombre: 'Apulo (Cundinamarca)', codigo: '25599' },
  { nombre: 'Ricaurte (Cundinamarca)', codigo: '25612' },
  { nombre: 'San Antonio del Tequendama (Cundinamarca)', codigo: '25645' },
  { nombre: 'San Bernardo (Cundinamarca)', codigo: '25649' },
  { nombre: 'San Cayetano (Cundinamarca)', codigo: '25653' },
  { nombre: 'San Francisco (Cundinamarca)', codigo: '25658' },
  { nombre: 'San Juan de Rioseco (Cundinamarca)', codigo: '25662' },
  { nombre: 'Sasaima (Cundinamarca)', codigo: '25718' },
  { nombre: 'Sesquilé (Cundinamarca)', codigo: '25736' },
  { nombre: 'Sibaté (Cundinamarca)', codigo: '25740' },
  { nombre: 'Silvania (Cundinamarca)', codigo: '25743' },
  { nombre: 'Simijaca (Cundinamarca)', codigo: '25745' },
  { nombre: 'Soacha (Cundinamarca)', codigo: '25754' },
  { nombre: 'Sopó (Cundinamarca)', codigo: '25758' },
  { nombre: 'Subachoque (Cundinamarca)', codigo: '25769' },
  { nombre: 'Suesca (Cundinamarca)', codigo: '25772' },
  { nombre: 'Supatá (Cundinamarca)', codigo: '25777' },
  { nombre: 'Susa (Cundinamarca)', codigo: '25779' },
  { nombre: 'Sutatausa (Cundinamarca)', codigo: '25781' },
  { nombre: 'Tabio (Cundinamarca)', codigo: '25785' },
  { nombre: 'Tausa (Cundinamarca)', codigo: '25793' },
  { nombre: 'Tena (Cundinamarca)', codigo: '25797' },
  { nombre: 'Tenjo (Cundinamarca)', codigo: '25799' },
  { nombre: 'Tibacuy (Cundinamarca)', codigo: '25805' },
  { nombre: 'Tibirita (Cundinamarca)', codigo: '25807' },
  { nombre: 'Tocaima (Cundinamarca)', codigo: '25815' },
  { nombre: 'Tocancipá (Cundinamarca)', codigo: '25817' },
  { nombre: 'Topaipí (Cundinamarca)', codigo: '25823' },
  { nombre: 'Ubalá (Cundinamarca)', codigo: '25839' },
  { nombre: 'Ubaque (Cundinamarca)', codigo: '25841' },
  { nombre: 'Villa de San Diego de Ubaté (Cundinamarca)', codigo: '25843' },
  { nombre: 'Une (Cundinamarca)', codigo: '25845' },
  { nombre: 'Útica (Cundinamarca)', codigo: '25851' },
  { nombre: 'Vergara (Cundinamarca)', codigo: '25862' },
  { nombre: 'Vianí (Cundinamarca)', codigo: '25867' },
  { nombre: 'Villagómez (Cundinamarca)', codigo: '25871' },
  { nombre: 'Villapinzón (Cundinamarca)', codigo: '25873' },
  { nombre: 'Villeta (Cundinamarca)', codigo: '25875' },
  { nombre: 'Viotá (Cundinamarca)', codigo: '25878' },
  { nombre: 'Yacopí (Cundinamarca)', codigo: '25885' },
  { nombre: 'Zipacón (Cundinamarca)', codigo: '25898' },
  { nombre: 'Zipaquirá (Cundinamarca)', codigo: '25899' },
  { nombre: 'Montería (Córdoba)', codigo: '23001' },
  { nombre: 'Ayapel (Córdoba)', codigo: '23068' },
  { nombre: 'Buenavista (Córdoba)', codigo: '23079' },
  { nombre: 'Canalete (Córdoba)', codigo: '23090' },
  { nombre: 'Cereté (Córdoba)', codigo: '23162' },
  { nombre: 'Chimá (Córdoba)', codigo: '23168' },
  { nombre: 'Chinú (Córdoba)', codigo: '23182' },
  { nombre: 'Ciénaga de Oro (Córdoba)', codigo: '23189' },
  { nombre: 'Cotorra (Córdoba)', codigo: '23300' },
  { nombre: 'La Apartada (Córdoba)', codigo: '23350' },
  { nombre: 'Lorica (Córdoba)', codigo: '23417' },
  { nombre: 'Los Córdobas (Córdoba)', codigo: '23419' },
  { nombre: 'Momil (Córdoba)', codigo: '23464' },
  { nombre: 'Montelíbano (Córdoba)', codigo: '23466' },
  { nombre: 'Moñitos (Córdoba)', codigo: '23500' },
  { nombre: 'Planeta Rica (Córdoba)', codigo: '23555' },
  { nombre: 'Pueblo Nuevo (Córdoba)', codigo: '23570' },
  { nombre: 'Puerto Escondido (Córdoba)', codigo: '23574' },
  { nombre: 'Puerto Libertador (Córdoba)', codigo: '23580' },
  { nombre: 'Purísima de la Concepción (Córdoba)', codigo: '23586' },
  { nombre: 'Sahagún (Córdoba)', codigo: '23660' },
  { nombre: 'San Andrés de Sotavento (Córdoba)', codigo: '23670' },
  { nombre: 'San Antero (Córdoba)', codigo: '23672' },
  { nombre: 'San Bernardo del Viento (Córdoba)', codigo: '23675' },
  { nombre: 'San Carlos (Córdoba)', codigo: '23678' },
  { nombre: 'San José de Uré (Córdoba)', codigo: '23682' },
  { nombre: 'San Pelayo (Córdoba)', codigo: '23686' },
  { nombre: 'Tierralta (Córdoba)', codigo: '23807' },
  { nombre: 'Tuchín (Córdoba)', codigo: '23815' },
  { nombre: 'Valencia (Córdoba)', codigo: '23855' },
  { nombre: 'Inírida (Guainía)', codigo: '94001' },
  { nombre: 'Barrancominas (Guainía)', codigo: '94343' },
  { nombre: 'Mapiripana (Guainía)', codigo: '94663' },
  { nombre: 'San Felipe (Guainía)', codigo: '94883' },
  { nombre: 'Puerto Colombia (Guainía)', codigo: '94884' },
  { nombre: 'La Guadalupe (Guainía)', codigo: '94885' },
  { nombre: 'Cacahual (Guainía)', codigo: '94886' },
  { nombre: 'Pana Pana (Guainía)', codigo: '94887' },
  { nombre: 'Morichal (Guainía)', codigo: '94888' },
  { nombre: 'San José del Guaviare (Guaviare)', codigo: '95001' },
  { nombre: 'Calamar (Guaviare)', codigo: '95015' },
  { nombre: 'El Retorno (Guaviare)', codigo: '95025' },
  { nombre: 'Miraflores (Guaviare)', codigo: '95200' },
  { nombre: 'Neiva (Huila)', codigo: '41001' },
  { nombre: 'Acevedo (Huila)', codigo: '41006' },
  { nombre: 'Agrado (Huila)', codigo: '41013' },
  { nombre: 'Aipe (Huila)', codigo: '41016' },
  { nombre: 'Algeciras (Huila)', codigo: '41020' },
  { nombre: 'Altamira (Huila)', codigo: '41026' },
  { nombre: 'Baraya (Huila)', codigo: '41078' },
  { nombre: 'Campoalegre (Huila)', codigo: '41132' },
  { nombre: 'Colombia (Huila)', codigo: '41206' },
  { nombre: 'Elías (Huila)', codigo: '41244' },
  { nombre: 'Garzón (Huila)', codigo: '41298' },
  { nombre: 'Gigante (Huila)', codigo: '41306' },
  { nombre: 'Guadalupe (Huila)', codigo: '41319' },
  { nombre: 'Hobo (Huila)', codigo: '41349' },
  { nombre: 'Íquira (Huila)', codigo: '41357' },
  { nombre: 'Isnos (Huila)', codigo: '41359' },
  { nombre: 'La Argentina (Huila)', codigo: '41378' },
  { nombre: 'La Plata (Huila)', codigo: '41396' },
  { nombre: 'Nátaga (Huila)', codigo: '41483' },
  { nombre: 'Oporapa (Huila)', codigo: '41503' },
  { nombre: 'Paicol (Huila)', codigo: '41518' },
  { nombre: 'Palermo (Huila)', codigo: '41524' },
  { nombre: 'Palestina (Huila)', codigo: '41530' },
  { nombre: 'Pital (Huila)', codigo: '41548' },
  { nombre: 'Pitalito (Huila)', codigo: '41551' },
  { nombre: 'Rivera (Huila)', codigo: '41615' },
  { nombre: 'Saladoblanco (Huila)', codigo: '41660' },
  { nombre: 'San Agustín (Huila)', codigo: '41668' },
  { nombre: 'Santa María (Huila)', codigo: '41676' },
  { nombre: 'Suaza (Huila)', codigo: '41770' },
  { nombre: 'Tarqui (Huila)', codigo: '41791' },
  { nombre: 'Tesalia (Huila)', codigo: '41797' },
  { nombre: 'Tello (Huila)', codigo: '41799' },
  { nombre: 'Teruel (Huila)', codigo: '41801' },
  { nombre: 'Timaná (Huila)', codigo: '41807' },
  { nombre: 'Villavieja (Huila)', codigo: '41872' },
  { nombre: 'Yaguará (Huila)', codigo: '41885' },
  { nombre: 'Riohacha (La Guajira)', codigo: '44001' },
  { nombre: 'Albania (La Guajira)', codigo: '44035' },
  { nombre: 'Barrancas (La Guajira)', codigo: '44078' },
  { nombre: 'Dibulla (La Guajira)', codigo: '44090' },
  { nombre: 'Distracción (La Guajira)', codigo: '44098' },
  { nombre: 'El Molino (La Guajira)', codigo: '44110' },
  { nombre: 'Fonseca (La Guajira)', codigo: '44279' },
  { nombre: 'Hatonuevo (La Guajira)', codigo: '44378' },
  { nombre: 'La Jagua del Pilar (La Guajira)', codigo: '44420' },
  { nombre: 'Maicao (La Guajira)', codigo: '44430' },
  { nombre: 'Manaure (La Guajira)', codigo: '44560' },
  { nombre: 'San Juan del Cesar (La Guajira)', codigo: '44650' },
  { nombre: 'Uribia (La Guajira)', codigo: '44847' },
  { nombre: 'Urumita (La Guajira)', codigo: '44855' },
  { nombre: 'Villanueva (La Guajira)', codigo: '44874' },
  { nombre: 'Santa Marta (Magdalena)', codigo: '47001' },
  { nombre: 'Algarrobo (Magdalena)', codigo: '47030' },
  { nombre: 'Aracataca (Magdalena)', codigo: '47053' },
  { nombre: 'Ariguaní (Magdalena)', codigo: '47058' },
  { nombre: 'Cerro de San Antonio (Magdalena)', codigo: '47161' },
  { nombre: 'Chivolo (Magdalena)', codigo: '47170' },
  { nombre: 'Ciénaga (Magdalena)', codigo: '47189' },
  { nombre: 'Concordia (Magdalena)', codigo: '47205' },
  { nombre: 'El Banco (Magdalena)', codigo: '47245' },
  { nombre: 'El Piñón (Magdalena)', codigo: '47258' },
  { nombre: 'El Retén (Magdalena)', codigo: '47268' },
  { nombre: 'Fundación (Magdalena)', codigo: '47288' },
  { nombre: 'Guamal (Magdalena)', codigo: '47318' },
  { nombre: 'Nueva Granada (Magdalena)', codigo: '47460' },
  { nombre: 'Pedraza (Magdalena)', codigo: '47541' },
  { nombre: 'Pijiño del Carmen (Magdalena)', codigo: '47545' },
  { nombre: 'Pivijay (Magdalena)', codigo: '47551' },
  { nombre: 'Plato (Magdalena)', codigo: '47555' },
  { nombre: 'Puebloviejo (Magdalena)', codigo: '47570' },
  { nombre: 'Remolino (Magdalena)', codigo: '47605' },
  { nombre: 'Sabanas de San Ángel (Magdalena)', codigo: '47660' },
  { nombre: 'Salamina (Magdalena)', codigo: '47675' },
  { nombre: 'San Sebastián de Buenavista (Magdalena)', codigo: '47692' },
  { nombre: 'San Zenón (Magdalena)', codigo: '47703' },
  { nombre: 'Santa Ana (Magdalena)', codigo: '47707' },
  { nombre: 'Santa Bárbara de Pinto (Magdalena)', codigo: '47720' },
  { nombre: 'Sitionuevo (Magdalena)', codigo: '47745' },
  { nombre: 'Tenerife (Magdalena)', codigo: '47798' },
  { nombre: 'Zapayán (Magdalena)', codigo: '47960' },
  { nombre: 'Zona Bananera (Magdalena)', codigo: '47980' },
  { nombre: 'Villavicencio (Meta)', codigo: '50001' },
  { nombre: 'Acacías (Meta)', codigo: '50006' },
  { nombre: 'Barranca de Upía (Meta)', codigo: '50110' },
  { nombre: 'Cabuyaro (Meta)', codigo: '50124' },
  { nombre: 'Castilla la Nueva (Meta)', codigo: '50150' },
  { nombre: 'Cubarral (Meta)', codigo: '50223' },
  { nombre: 'Cumaral (Meta)', codigo: '50226' },
  { nombre: 'El Calvario (Meta)', codigo: '50245' },
  { nombre: 'El Castillo (Meta)', codigo: '50251' },
  { nombre: 'El Dorado (Meta)', codigo: '50270' },
  { nombre: 'Fuente de Oro (Meta)', codigo: '50287' },
  { nombre: 'Granada (Meta)', codigo: '50313' },
  { nombre: 'Guamal (Meta)', codigo: '50318' },
  { nombre: 'Mapiripán (Meta)', codigo: '50325' },
  { nombre: 'Mesetas (Meta)', codigo: '50330' },
  { nombre: 'La Macarena (Meta)', codigo: '50350' },
  { nombre: 'Uribe (Meta)', codigo: '50370' },
  { nombre: 'Lejanías (Meta)', codigo: '50400' },
  { nombre: 'Puerto Concordia (Meta)', codigo: '50450' },
  { nombre: 'Puerto Gaitán (Meta)', codigo: '50568' },
  { nombre: 'Puerto López (Meta)', codigo: '50573' },
  { nombre: 'Puerto Lleras (Meta)', codigo: '50577' },
  { nombre: 'Puerto Rico (Meta)', codigo: '50590' },
  { nombre: 'Restrepo (Meta)', codigo: '50606' },
  { nombre: 'San Carlos de Guaroa (Meta)', codigo: '50680' },
  { nombre: 'San Juan de Arama (Meta)', codigo: '50683' },
  { nombre: 'San Juanito (Meta)', codigo: '50686' },
  { nombre: 'San Martín (Meta)', codigo: '50689' },
  { nombre: 'Vistahermosa (Meta)', codigo: '50711' },
  { nombre: 'Pasto (Nariño)', codigo: '52001' },
  { nombre: 'Albán (Nariño)', codigo: '52019' },
  { nombre: 'Aldana (Nariño)', codigo: '52022' },
  { nombre: 'Ancuya (Nariño)', codigo: '52036' },
  { nombre: 'Arboleda (Nariño)', codigo: '52051' },
  { nombre: 'Barbacoas (Nariño)', codigo: '52079' },
  { nombre: 'Belén (Nariño)', codigo: '52083' },
  { nombre: 'Buesaco (Nariño)', codigo: '52110' },
  { nombre: 'Colón (Nariño)', codigo: '52203' },
  { nombre: 'Consacá (Nariño)', codigo: '52207' },
  { nombre: 'Contadero (Nariño)', codigo: '52210' },
  { nombre: 'Córdoba (Nariño)', codigo: '52215' },
  { nombre: 'Cuaspud Carlosama (Nariño)', codigo: '52224' },
  { nombre: 'Cumbal (Nariño)', codigo: '52227' },
  { nombre: 'Cumbitara (Nariño)', codigo: '52233' },
  { nombre: 'Chachagüí (Nariño)', codigo: '52240' },
  { nombre: 'El Charco (Nariño)', codigo: '52250' },
  { nombre: 'El Peñol (Nariño)', codigo: '52254' },
  { nombre: 'El Rosario (Nariño)', codigo: '52256' },
  { nombre: 'El Tablón de Gómez (Nariño)', codigo: '52258' },
  { nombre: 'El Tambo (Nariño)', codigo: '52260' },
  { nombre: 'Funes (Nariño)', codigo: '52287' },
  { nombre: 'Guachucal (Nariño)', codigo: '52317' },
  { nombre: 'Guaitarilla (Nariño)', codigo: '52320' },
  { nombre: 'Gualmatán (Nariño)', codigo: '52323' },
  { nombre: 'Iles (Nariño)', codigo: '52352' },
  { nombre: 'Imués (Nariño)', codigo: '52354' },
  { nombre: 'Ipiales (Nariño)', codigo: '52356' },
  { nombre: 'Jardines de Sucumbíos (Nariño)', codigo: '52360' },
  { nombre: 'La Cruz (Nariño)', codigo: '52378' },
  { nombre: 'La Florida (Nariño)', codigo: '52381' },
  { nombre: 'La Llanada (Nariño)', codigo: '52385' },
  { nombre: 'La Tola (Nariño)', codigo: '52390' },
  { nombre: 'La Unión (Nariño)', codigo: '52399' },
  { nombre: 'Leiva (Nariño)', codigo: '52405' },
  { nombre: 'Linares (Nariño)', codigo: '52411' },
  { nombre: 'Los Andes (Nariño)', codigo: '52418' },
  { nombre: 'Magüí (Nariño)', codigo: '52427' },
  { nombre: 'Mallama (Nariño)', codigo: '52435' },
  { nombre: 'Mosquera (Nariño)', codigo: '52473' },
  { nombre: 'Nariño (Nariño)', codigo: '52480' },
  { nombre: 'Olaya Herrera (Nariño)', codigo: '52490' },
  { nombre: 'Ospina (Nariño)', codigo: '52506' },
  { nombre: 'Francisco Pizarro (Nariño)', codigo: '52520' },
  { nombre: 'Policarpa (Nariño)', codigo: '52540' },
  { nombre: 'Potosí (Nariño)', codigo: '52560' },
  { nombre: 'Providencia (Nariño)', codigo: '52565' },
  { nombre: 'Puerres (Nariño)', codigo: '52573' },
  { nombre: 'Pupiales (Nariño)', codigo: '52585' },
  { nombre: 'Ricaurte (Nariño)', codigo: '52612' },
  { nombre: 'Roberto Payán (Nariño)', codigo: '52621' },
  { nombre: 'Samaniego (Nariño)', codigo: '52678' },
  { nombre: 'Sandoná (Nariño)', codigo: '52683' },
  { nombre: 'San Bernardo (Nariño)', codigo: '52685' },
  { nombre: 'San Lorenzo (Nariño)', codigo: '52687' },
  { nombre: 'San Pablo (Nariño)', codigo: '52693' },
  { nombre: 'San Pedro de Cartago (Nariño)', codigo: '52694' },
  { nombre: 'Santa Bárbara (Nariño)', codigo: '52696' },
  { nombre: 'Santacruz (Nariño)', codigo: '52699' },
  { nombre: 'Sapuyes (Nariño)', codigo: '52720' },
  { nombre: 'Taminango (Nariño)', codigo: '52786' },
  { nombre: 'Tangua (Nariño)', codigo: '52788' },
  { nombre: 'San Andrés de Tumaco (Nariño)', codigo: '52835' },
  { nombre: 'Túquerres (Nariño)', codigo: '52838' },
  { nombre: 'Yacuanquer (Nariño)', codigo: '52885' },
  { nombre: 'Cúcuta (Norte de Santander)', codigo: '54001' },
  { nombre: 'Ábrego (Norte de Santander)', codigo: '54003' },
  { nombre: 'Arboledas (Norte de Santander)', codigo: '54051' },
  { nombre: 'Bochalema (Norte de Santander)', codigo: '54099' },
  { nombre: 'Bucarasica (Norte de Santander)', codigo: '54109' },
  { nombre: 'Cácota (Norte de Santander)', codigo: '54125' },
  { nombre: 'Cáchira (Norte de Santander)', codigo: '54128' },
  { nombre: 'Chinácota (Norte de Santander)', codigo: '54172' },
  { nombre: 'Chitagá (Norte de Santander)', codigo: '54174' },
  { nombre: 'Convención (Norte de Santander)', codigo: '54206' },
  { nombre: 'Cucutilla (Norte de Santander)', codigo: '54223' },
  { nombre: 'Durania (Norte de Santander)', codigo: '54239' },
  { nombre: 'El Carmen (Norte de Santander)', codigo: '54245' },
  { nombre: 'El Tarra (Norte de Santander)', codigo: '54250' },
  { nombre: 'El Zulia (Norte de Santander)', codigo: '54261' },
  { nombre: 'Gramalote (Norte de Santander)', codigo: '54313' },
  { nombre: 'Hacarí (Norte de Santander)', codigo: '54344' },
  { nombre: 'Herrán (Norte de Santander)', codigo: '54347' },
  { nombre: 'Labateca (Norte de Santander)', codigo: '54377' },
  { nombre: 'La Esperanza (Norte de Santander)', codigo: '54385' },
  { nombre: 'La Playa (Norte de Santander)', codigo: '54398' },
  { nombre: 'Los Patios (Norte de Santander)', codigo: '54405' },
  { nombre: 'Lourdes (Norte de Santander)', codigo: '54418' },
  { nombre: 'Mutiscua (Norte de Santander)', codigo: '54480' },
  { nombre: 'Ocaña (Norte de Santander)', codigo: '54498' },
  { nombre: 'Pamplona (Norte de Santander)', codigo: '54518' },
  { nombre: 'Pamplonita (Norte de Santander)', codigo: '54520' },
  { nombre: 'Puerto Santander (Norte de Santander)', codigo: '54553' },
  { nombre: 'Ragonvalia (Norte de Santander)', codigo: '54599' },
  { nombre: 'Salazar (Norte de Santander)', codigo: '54660' },
  { nombre: 'San Calixto (Norte de Santander)', codigo: '54670' },
  { nombre: 'San Cayetano (Norte de Santander)', codigo: '54673' },
  { nombre: 'Santiago (Norte de Santander)', codigo: '54680' },
  { nombre: 'Sardinata (Norte de Santander)', codigo: '54720' },
  { nombre: 'Silos (Norte de Santander)', codigo: '54743' },
  { nombre: 'Teorama (Norte de Santander)', codigo: '54800' },
  { nombre: 'Tibú (Norte de Santander)', codigo: '54810' },
  { nombre: 'Toledo (Norte de Santander)', codigo: '54820' },
  { nombre: 'Villa Caro (Norte de Santander)', codigo: '54871' },
  { nombre: 'Villa del Rosario (Norte de Santander)', codigo: '54874' },
  { nombre: 'Mocoa (Putumayo)', codigo: '86001' },
  { nombre: 'Colón (Putumayo)', codigo: '86219' },
  { nombre: 'Orito (Putumayo)', codigo: '86320' },
  { nombre: 'Puerto Asís (Putumayo)', codigo: '86568' },
  { nombre: 'Puerto Caicedo (Putumayo)', codigo: '86569' },
  { nombre: 'Puerto Guzmán (Putumayo)', codigo: '86571' },
  { nombre: 'Puerto Leguízamo (Putumayo)', codigo: '86573' },
  { nombre: 'Sibundoy (Putumayo)', codigo: '86749' },
  { nombre: 'San Francisco (Putumayo)', codigo: '86755' },
  { nombre: 'San Miguel (Putumayo)', codigo: '86757' },
  { nombre: 'Santiago (Putumayo)', codigo: '86760' },
  { nombre: 'Valle del Guamuez (Putumayo)', codigo: '86865' },
  { nombre: 'Villagarzón (Putumayo)', codigo: '86885' },
  { nombre: 'Armenia (Quindío)', codigo: '63001' },
  { nombre: 'Buenavista (Quindío)', codigo: '63111' },
  { nombre: 'Calarcá (Quindío)', codigo: '63130' },
  { nombre: 'Circasia (Quindío)', codigo: '63190' },
  { nombre: 'Córdoba (Quindío)', codigo: '63212' },
  { nombre: 'Filandia (Quindío)', codigo: '63272' },
  { nombre: 'Génova (Quindío)', codigo: '63302' },
  { nombre: 'La Tebaida (Quindío)', codigo: '63401' },
  { nombre: 'Montenegro (Quindío)', codigo: '63470' },
  { nombre: 'Pijao (Quindío)', codigo: '63548' },
  { nombre: 'Quimbaya (Quindío)', codigo: '63594' },
  { nombre: 'Salento (Quindío)', codigo: '63690' },
  { nombre: 'Pereira (Risaralda)', codigo: '66001' },
  { nombre: 'Apía (Risaralda)', codigo: '66045' },
  { nombre: 'Balboa (Risaralda)', codigo: '66075' },
  { nombre: 'Belén de Umbría (Risaralda)', codigo: '66088' },
  { nombre: 'Dosquebradas (Risaralda)', codigo: '66170' },
  { nombre: 'Guática (Risaralda)', codigo: '66318' },
  { nombre: 'La Celia (Risaralda)', codigo: '66383' },
  { nombre: 'La Virginia (Risaralda)', codigo: '66400' },
  { nombre: 'Marsella (Risaralda)', codigo: '66440' },
  { nombre: 'Mistrató (Risaralda)', codigo: '66456' },
  { nombre: 'Pueblo Rico (Risaralda)', codigo: '66572' },
  { nombre: 'Quinchía (Risaralda)', codigo: '66594' },
  { nombre: 'Santa Rosa de Cabal (Risaralda)', codigo: '66682' },
  { nombre: 'Santuario (Risaralda)', codigo: '66687' },
  { nombre: 'Bucaramanga (Santander)', codigo: '68001' },
  { nombre: 'Aguada (Santander)', codigo: '68013' },
  { nombre: 'Albania (Santander)', codigo: '68020' },
  { nombre: 'Aratoca (Santander)', codigo: '68051' },
  { nombre: 'Barbosa (Santander)', codigo: '68077' },
  { nombre: 'Barichara (Santander)', codigo: '68079' },
  { nombre: 'Barrancabermeja (Santander)', codigo: '68081' },
  { nombre: 'Betulia (Santander)', codigo: '68092' },
  { nombre: 'Bolívar (Santander)', codigo: '68101' },
  { nombre: 'Cabrera (Santander)', codigo: '68121' },
  { nombre: 'California (Santander)', codigo: '68132' },
  { nombre: 'Capitanejo (Santander)', codigo: '68147' },
  { nombre: 'Carcasí (Santander)', codigo: '68152' },
  { nombre: 'Cepitá (Santander)', codigo: '68160' },
  { nombre: 'Cerrito (Santander)', codigo: '68162' },
  { nombre: 'Charalá (Santander)', codigo: '68167' },
  { nombre: 'Charta (Santander)', codigo: '68169' },
  { nombre: 'Chima (Santander)', codigo: '68176' },
  { nombre: 'Chipatá (Santander)', codigo: '68179' },
  { nombre: 'Cimitarra (Santander)', codigo: '68190' },
  { nombre: 'Concepción (Santander)', codigo: '68207' },
  { nombre: 'Confines (Santander)', codigo: '68209' },
  { nombre: 'Contratación (Santander)', codigo: '68211' },
  { nombre: 'Coromoro (Santander)', codigo: '68217' },
  { nombre: 'Curití (Santander)', codigo: '68229' },
  { nombre: 'El Carmen de Chucurí (Santander)', codigo: '68235' },
  { nombre: 'El Guacamayo (Santander)', codigo: '68245' },
  { nombre: 'El Peñón (Santander)', codigo: '68250' },
  { nombre: 'El Playón (Santander)', codigo: '68255' },
  { nombre: 'Encino (Santander)', codigo: '68264' },
  { nombre: 'Enciso (Santander)', codigo: '68266' },
  { nombre: 'Florián (Santander)', codigo: '68271' },
  { nombre: 'Floridablanca (Santander)', codigo: '68276' },
  { nombre: 'Galán (Santander)', codigo: '68296' },
  { nombre: 'Gámbita (Santander)', codigo: '68298' },
  { nombre: 'Girón (Santander)', codigo: '68307' },
  { nombre: 'Guaca (Santander)', codigo: '68318' },
  { nombre: 'Guadalupe (Santander)', codigo: '68320' },
  { nombre: 'Guapotá (Santander)', codigo: '68322' },
  { nombre: 'Guavatá (Santander)', codigo: '68324' },
  { nombre: 'Güepsa (Santander)', codigo: '68327' },
  { nombre: 'Hato (Santander)', codigo: '68344' },
  { nombre: 'Jesús María (Santander)', codigo: '68368' },
  { nombre: 'Jordán (Santander)', codigo: '68370' },
  { nombre: 'La Belleza (Santander)', codigo: '68377' },
  { nombre: 'Landázuri (Santander)', codigo: '68385' },
  { nombre: 'La Paz (Santander)', codigo: '68397' },
  { nombre: 'Lebrija (Santander)', codigo: '68406' },
  { nombre: 'Los Santos (Santander)', codigo: '68418' },
  { nombre: 'Macaravita (Santander)', codigo: '68425' },
  { nombre: 'Málaga (Santander)', codigo: '68432' },
  { nombre: 'Matanza (Santander)', codigo: '68444' },
  { nombre: 'Mogotes (Santander)', codigo: '68464' },
  { nombre: 'Molagavita (Santander)', codigo: '68468' },
  { nombre: 'Ocamonte (Santander)', codigo: '68498' },
  { nombre: 'Oiba (Santander)', codigo: '68500' },
  { nombre: 'Onzaga (Santander)', codigo: '68502' },
  { nombre: 'Palmar (Santander)', codigo: '68522' },
  { nombre: 'Palmas del Socorro (Santander)', codigo: '68524' },
  { nombre: 'Páramo (Santander)', codigo: '68533' },
  { nombre: 'Piedecuesta (Santander)', codigo: '68547' },
  { nombre: 'Pinchote (Santander)', codigo: '68549' },
  { nombre: 'Puente Nacional (Santander)', codigo: '68572' },
  { nombre: 'Puerto Parra (Santander)', codigo: '68573' },
  { nombre: 'Puerto Wilches (Santander)', codigo: '68575' },
  { nombre: 'Rionegro (Santander)', codigo: '68615' },
  { nombre: 'Sabana de Torres (Santander)', codigo: '68655' },
  { nombre: 'San Andrés (Santander)', codigo: '68669' },
  { nombre: 'San Benito (Santander)', codigo: '68673' },
  { nombre: 'San Gil (Santander)', codigo: '68679' },
  { nombre: 'San Joaquín (Santander)', codigo: '68682' },
  { nombre: 'San José de Miranda (Santander)', codigo: '68684' },
  { nombre: 'San Miguel (Santander)', codigo: '68686' },
  { nombre: 'San Vicente de Chucurí (Santander)', codigo: '68689' },
  { nombre: 'Santa Bárbara (Santander)', codigo: '68705' },
  { nombre: 'Santa Helena del Opón (Santander)', codigo: '68720' },
  { nombre: 'Simacota (Santander)', codigo: '68745' },
  { nombre: 'Socorro (Santander)', codigo: '68755' },
  { nombre: 'Suaita (Santander)', codigo: '68770' },
  { nombre: 'Sucre (Santander)', codigo: '68773' },
  { nombre: 'Suratá (Santander)', codigo: '68780' },
  { nombre: 'Tona (Santander)', codigo: '68820' },
  { nombre: 'Valle de San José (Santander)', codigo: '68855' },
  { nombre: 'Vélez (Santander)', codigo: '68861' },
  { nombre: 'Vetas (Santander)', codigo: '68867' },
  { nombre: 'Villanueva (Santander)', codigo: '68872' },
  { nombre: 'Zapatoca (Santander)', codigo: '68895' },
  { nombre: 'Sincelejo (Sucre)', codigo: '70001' },
  { nombre: 'Buenavista (Sucre)', codigo: '70110' },
  { nombre: 'Caimito (Sucre)', codigo: '70124' },
  { nombre: 'Colosó (Sucre)', codigo: '70204' },
  { nombre: 'Corozal (Sucre)', codigo: '70215' },
  { nombre: 'Coveñas (Sucre)', codigo: '70221' },
  { nombre: 'Chalán (Sucre)', codigo: '70230' },
  { nombre: 'El Roble (Sucre)', codigo: '70233' },
  { nombre: 'Galeras (Sucre)', codigo: '70235' },
  { nombre: 'Guaranda (Sucre)', codigo: '70265' },
  { nombre: 'La Unión (Sucre)', codigo: '70400' },
  { nombre: 'Los Palmitos (Sucre)', codigo: '70418' },
  { nombre: 'Majagual (Sucre)', codigo: '70429' },
  { nombre: 'Morroa (Sucre)', codigo: '70473' },
  { nombre: 'Ovejas (Sucre)', codigo: '70508' },
  { nombre: 'Palmito (Sucre)', codigo: '70523' },
  { nombre: 'Sampués (Sucre)', codigo: '70670' },
  { nombre: 'San Benito Abad (Sucre)', codigo: '70678' },
  { nombre: 'San Juan de Betulia (Sucre)', codigo: '70702' },
  { nombre: 'San Marcos (Sucre)', codigo: '70708' },
  { nombre: 'San Onofre (Sucre)', codigo: '70713' },
  { nombre: 'San Pedro (Sucre)', codigo: '70717' },
  { nombre: 'San Luis de Sincé (Sucre)', codigo: '70742' },
  { nombre: 'Sucre (Sucre)', codigo: '70771' },
  { nombre: 'Santiago de Tolú (Sucre)', codigo: '70820' },
  { nombre: 'San José de Toluviejo (Sucre)', codigo: '70823' },
  { nombre: 'Ibagué (Tolima)', codigo: '73001' },
  { nombre: 'Alpujarra (Tolima)', codigo: '73024' },
  { nombre: 'Alvarado (Tolima)', codigo: '73026' },
  { nombre: 'Ambalema (Tolima)', codigo: '73030' },
  { nombre: 'Anzoátegui (Tolima)', codigo: '73043' },
  { nombre: 'Armero (Tolima)', codigo: '73055' },
  { nombre: 'Ataco (Tolima)', codigo: '73067' },
  { nombre: 'Cajamarca (Tolima)', codigo: '73124' },
  { nombre: 'Carmen de Apicalá (Tolima)', codigo: '73148' },
  { nombre: 'Casabianca (Tolima)', codigo: '73152' },
  { nombre: 'Chaparral (Tolima)', codigo: '73168' },
  { nombre: 'Coello (Tolima)', codigo: '73200' },
  { nombre: 'Coyaima (Tolima)', codigo: '73217' },
  { nombre: 'Cunday (Tolima)', codigo: '73226' },
  { nombre: 'Dolores (Tolima)', codigo: '73236' },
  { nombre: 'Espinal (Tolima)', codigo: '73268' },
  { nombre: 'Falan (Tolima)', codigo: '73270' },
  { nombre: 'Flandes (Tolima)', codigo: '73275' },
  { nombre: 'Fresno (Tolima)', codigo: '73283' },
  { nombre: 'Guamo (Tolima)', codigo: '73319' },
  { nombre: 'Herveo (Tolima)', codigo: '73347' },
  { nombre: 'Honda (Tolima)', codigo: '73349' },
  { nombre: 'Icononzo (Tolima)', codigo: '73352' },
  { nombre: 'Lérida (Tolima)', codigo: '73408' },
  { nombre: 'Líbano (Tolima)', codigo: '73411' },
  { nombre: 'San Sebastián de Mariquita (Tolima)', codigo: '73443' },
  { nombre: 'Melgar (Tolima)', codigo: '73449' },
  { nombre: 'Murillo (Tolima)', codigo: '73461' },
  { nombre: 'Natagaima (Tolima)', codigo: '73483' },
  { nombre: 'Ortega (Tolima)', codigo: '73504' },
  { nombre: 'Palocabildo (Tolima)', codigo: '73520' },
  { nombre: 'Piedras (Tolima)', codigo: '73547' },
  { nombre: 'Planadas (Tolima)', codigo: '73555' },
  { nombre: 'Prado (Tolima)', codigo: '73563' },
  { nombre: 'Purificación (Tolima)', codigo: '73585' },
  { nombre: 'Rioblanco (Tolima)', codigo: '73616' },
  { nombre: 'Roncesvalles (Tolima)', codigo: '73622' },
  { nombre: 'Rovira (Tolima)', codigo: '73624' },
  { nombre: 'Saldaña (Tolima)', codigo: '73671' },
  { nombre: 'San Antonio (Tolima)', codigo: '73675' },
  { nombre: 'San Luis (Tolima)', codigo: '73678' },
  { nombre: 'Santa Isabel (Tolima)', codigo: '73686' },
  { nombre: 'Suárez (Tolima)', codigo: '73770' },
  { nombre: 'Valle de San Juan (Tolima)', codigo: '73854' },
  { nombre: 'Venadillo (Tolima)', codigo: '73861' },
  { nombre: 'Villahermosa (Tolima)', codigo: '73870' },
  { nombre: 'Villarrica (Tolima)', codigo: '73873' },
  { nombre: 'Cali (Valle del Cauca)', codigo: '76001' },
  { nombre: 'Alcalá (Valle del Cauca)', codigo: '76020' },
  { nombre: 'Andalucía (Valle del Cauca)', codigo: '76036' },
  { nombre: 'Ansermanuevo (Valle del Cauca)', codigo: '76041' },
  { nombre: 'Argelia (Valle del Cauca)', codigo: '76054' },
  { nombre: 'Bolívar (Valle del Cauca)', codigo: '76100' },
  { nombre: 'Buenaventura (Valle del Cauca)', codigo: '76109' },
  { nombre: 'Guadalajara de Buga (Valle del Cauca)', codigo: '76111' },
  { nombre: 'Bugalagrande (Valle del Cauca)', codigo: '76113' },
  { nombre: 'Caicedonia (Valle del Cauca)', codigo: '76122' },
  { nombre: 'Calima (Valle del Cauca)', codigo: '76126' },
  { nombre: 'Candelaria (Valle del Cauca)', codigo: '76130' },
  { nombre: 'Cartago (Valle del Cauca)', codigo: '76147' },
  { nombre: 'Dagua (Valle del Cauca)', codigo: '76233' },
  { nombre: 'El Águila (Valle del Cauca)', codigo: '76243' },
  { nombre: 'El Cairo (Valle del Cauca)', codigo: '76246' },
  { nombre: 'El Cerrito (Valle del Cauca)', codigo: '76248' },
  { nombre: 'El Dovio (Valle del Cauca)', codigo: '76250' },
  { nombre: 'Florida (Valle del Cauca)', codigo: '76275' },
  { nombre: 'Ginebra (Valle del Cauca)', codigo: '76306' },
  { nombre: 'Guacarí (Valle del Cauca)', codigo: '76318' },
  { nombre: 'Jamundí (Valle del Cauca)', codigo: '76364' },
  { nombre: 'La Cumbre (Valle del Cauca)', codigo: '76377' },
  { nombre: 'La Unión (Valle del Cauca)', codigo: '76400' },
  { nombre: 'La Victoria (Valle del Cauca)', codigo: '76403' },
  { nombre: 'Obando (Valle del Cauca)', codigo: '76497' },
  { nombre: 'Palmira (Valle del Cauca)', codigo: '76520' },
  { nombre: 'Pradera (Valle del Cauca)', codigo: '76563' },
  { nombre: 'Restrepo (Valle del Cauca)', codigo: '76606' },
  { nombre: 'Riofrío (Valle del Cauca)', codigo: '76616' },
  { nombre: 'Roldanillo (Valle del Cauca)', codigo: '76622' },
  { nombre: 'San Pedro (Valle del Cauca)', codigo: '76670' },
  { nombre: 'Sevilla (Valle del Cauca)', codigo: '76736' },
  { nombre: 'Toro (Valle del Cauca)', codigo: '76823' },
  { nombre: 'Trujillo (Valle del Cauca)', codigo: '76828' },
  { nombre: 'Tuluá (Valle del Cauca)', codigo: '76834' },
  { nombre: 'Ulloa (Valle del Cauca)', codigo: '76845' },
  { nombre: 'Versalles (Valle del Cauca)', codigo: '76863' },
  { nombre: 'Vijes (Valle del Cauca)', codigo: '76869' },
  { nombre: 'Yotoco (Valle del Cauca)', codigo: '76890' },
  { nombre: 'Yumbo (Valle del Cauca)', codigo: '76892' },
  { nombre: 'Zarzal (Valle del Cauca)', codigo: '76895' },
  { nombre: 'Mitú (Vaupés)', codigo: '97001' },
  { nombre: 'Carurú (Vaupés)', codigo: '97161' },
  { nombre: 'Pacoa (Vaupés)', codigo: '97511' },
  { nombre: 'Taraira (Vaupés)', codigo: '97666' },
  { nombre: 'Papunahua (Vaupés)', codigo: '97777' },
  { nombre: 'Yavaraté (Vaupés)', codigo: '97889' },
  { nombre: 'Puerto Carreño (Vichada)', codigo: '99001' },
  { nombre: 'La Primavera (Vichada)', codigo: '99524' },
  { nombre: 'Santa Rita (Vichada)', codigo: '99572' },
  { nombre: 'Santa Rosalía (Vichada)', codigo: '99624' },
  { nombre: 'San José de Ocune (Vichada)', codigo: '99760' },
  { nombre: 'Cumaribo (Vichada)', codigo: '99773' },
];
