interface DatosComunes {
  nombre: string;
  ruta: string;
  definicion: string;
}

interface DatosIndicador extends DatosComunes {
  archivo: string;
  mun: boolean;
  dep: boolean;
  explicacion: string;
  metodologia: string;
  unidad: string;
  fuente_numerador: string;
  fuente_denominador: string;
  desagregacion: string;
  contexto: string;
  interpretacion: string;
  umbral?: number;
}

interface DatosYa extends DatosComunes {
  imagen: string;
  indicadores: DatosIndicador[];
}

const datos: DatosYa[] = [
  {
    nombre: 'Salud y nutrición',
    ruta: 'salud-nutricion',
    imagen: 'ya1',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Cobertura de acueducto',
        ruta: 'acueducto',
        archivo: 'ya1-1',
        umbral: 92.9,
        mun: true,
        dep: true,
        explicacion: 'Indica el acceso potencial a agua potable para el consumo humano.',
        definicion:
          'Conjunto de sistemas de irrigación que permite transportar agua en forma de flujo continuo desde un lugar en el que es accesible en la naturaleza hasta un punto de consumo. Esta variable no está directamente asociada a la provisión de agua potable.',
        metodologia: 'Se desconoce, metodología propia del SUI.',
        unidad: 'Tasa (Es un cálculo potencial)',
        fuente_numerador: 'Sistema Único de Información de Servicios Públicos - SUI',
        fuente_denominador: 'Sistema Único de Información de Servicios Públicos - SUI',
        desagregacion: 'Municipal',
        contexto:
          'La pandemia de la COVID-19 ha resaltado la importancia del saneamiento, la higiene y el acceso a agua potable para prevenir y controlar enfermedades. La Organización Mundial de la Salud destaca que el lavado de manos es una medida altamente efectiva para reducir la propagación de patógenos A pesar de esto, Colombia aún carece de una cobertura universal de agua potable y saneamiento.',
        interpretacion:
          'Un valor de 70% significa que existen 70 familias que cuentan con acceso real a agua potable por cada 100 familias en un territorio y momento específicos. Más información sobre la importancia del acceso a agua potable: https://www.un.org/sustainabledevelopment/es/water-and-sanitation/#:~:text=Alcanzar%20la%20cobertura%20universal%20para,y%20tres%20para%20la%20higiene.',
      },
      {
        nombre: 'Cobertura de alcantarillado',
        ruta: 'alcantarillado',
        archivo: 'ya1-2',
        umbral: 57.4,
        mun: true,
        dep: true,
        explicacion: 'Indica el acceso potencial que tiene un hogar a una conexión de alcantarillado.',
        definicion:
          'Es el conjunto de conductos de subterráneos llamados alcantarillas, que transportan el agua residual o pluvial. Aguas residuales son las aguas gastas por la comunidad.',
        metodologia: 'Se desconoce, metodología propia del SUI.',
        unidad: 'Tasa (Es un cálculo potencial)',
        fuente_numerador: 'Sistema Único de Información de Servicios Públicos - SUI',
        fuente_denominador: 'Sistema Único de Información de Servicios Públicos - SUI',
        desagregacion: 'Municipal',
        contexto:
          'A pesar de los avances en la expansión del acceso a agua potable y saneamiento, aún hay cientos de colombianos que habitan principalmente en áreas rurales y carecen de estos servicios básicos. A nivel global, una de cada tres personas no tiene acceso a agua potable segura, dos de cada cinco no cuentan con instalaciones básicas para lavarse las manos, y más de 673 millones aún practican la defecación al aire libre.',
        interpretacion:
          'Un valor de 90% significa que existen 90 familias que cuentan con acceso real a alcantarillado por cada 100 familias en un territorio y momento específicos. Más información sobre alcantarillado y saneamiento: https://www.un.org/sustainabledevelopment/es/water-and-sanitation/#:~:text=Alcanzar%20la%20cobertura%20universal%20para,y%20tres%20para%20la%20higiene.',
      },
      {
        nombre: 'Mortalidad menores de 5 años (cualquier condición)',
        ruta: 'mortalidad',
        archivo: 'ya1-3',
        umbral: 15,
        mun: true,
        dep: true,
        explicacion: 'Indica el número de defunciones ocurridas en niños menores de 5 años por cada 1000 nacidos.',
        definicion: 'Indica el número de muertes por cualquier tipo de causa en menores de 5 años.',
        metodologia:
          'Número de muertes de menores de 5 años  por cualquier tipo de causa / Número total de menores de 5 años.',
        unidad: 'Por 100.000 menores de 5 años.',
        fuente_numerador: 'CUBO INDICADORES EEVV',
        fuente_denominador: 'CUBO INDICADORES EEVV',
        desagregacion: 'Municipal',
        contexto:
          'La mortalidad en menores de 5 años es un reflejo directo de las desigualdades sociales y económicas de un país. Por ejemplo, en países como Honduras o Haití los niños del 20% de la población más pobre tienen al menos el doble de probabilidad de morir antes de los 5 años, en comparación con los niños cuyas familias tienen mayores niveles de ingresos. Esto tiene que ver con la calidad de vida y el acceso afectivos a servicios de salud de calidad, así como también los niveles educativos de las personas cuidadoras.',
        interpretacion:
          'Un valor de 80, indica que murieron 80 niños menores de 5 años por cada 1.000 nacidos vivos en un momento y territorio específico.',
      },
      {
        nombre: 'Control prenatal',
        ruta: 'control-prenatal',
        archivo: 'ya1-5',
        umbral: 95,
        mun: true,
        dep: true,
        explicacion: '',
        definicion: 'Proporción de nacidos vivos con 4 o más controles prenatales.',
        metodologia:
          'Número de nacidos vivos cuyas gestantes asistieron a 4 o más controles prenatales / Total de nacidos vivos.',
        unidad: 'Por 100 (%)',
        fuente_numerador: 'CUBO INDICADORES EEVV',
        fuente_denominador: 'CUBO INDICADORES EEVV',
        desagregacion: 'Municipal',
        contexto:
          'La atención prenatal es fundamental para reducir el riesgo de muertes en los recién nacidos y en las gestantes. Es un indicador que expresa el acceso a los servicios de salud durante el embarazo, puesto que en la medida en que exista un mayor número de contactos de calidad entre las embarazadas y el personal de salud, se podrán reducir las complicaciones y riesgos durante esta etapa de la vida.',
        interpretacion:
          'Un valor de 7.4% indica que 7,4 de cada 100 nacidos vivos tuvieron 4 o más controles prenatales en un momento y territorio específicos.',
      },
      {
        nombre: 'Desnutrición aguda',
        ruta: 'desnutricion',
        archivo: 'ya1-7',
        umbral: 900,
        mun: true,
        dep: true,
        explicacion: '',
        definicion:
          'Proporción de niños menores de 5 años padecen de desnutrición aguda en un momento y territorio determinado.',
        metodologia:
          'Número de niños menores de 5 años que sufren de desnutrición aguda en un periodo y territorio específicos /  Número de nacidos vivos menores de 5 años en el mismo periodo y territorio.',
        unidad: 'Por 100 (%)',
        fuente_numerador: 'SIVIGILA',
        fuente_denominador: 'CUBO INDICADORES EEVV',
        desagregacion: 'Municipal',
        contexto:
          'El número de personas que sufren hambre en el mundo ha aumentado desde 2015, llegando a unos 690 millones, el 8,9% de la población global. Si las tendencias persisten, podría superar los 840 millones para 2030, alejándonos del objetivo de hambre cero. Factores como conflictos y la pandemia de COVID-19 han contribuido a que alrededor de 135 millones enfrenten hambre severa. Se necesitan acciones urgentes para proporcionar alimentos y ayuda humanitaria. Además, es crucial transformar el sistema agroalimentario global para alimentar a los afectados y a la creciente población mundial mediante prácticas sostenibles.',
        interpretacion:
          'Un valor de 15% indica que 15 de cada 100 nacidos vivos que son menores de 5 años sufren de desnutrición aguda en un momento y territorio específicos. https://www.un.org/sustainabledevelopment/es/hunger/',
      },
      {
        nombre: 'Bajo peso al nacer',
        ruta: 'bajo-peso',
        archivo: 'ya1-8',
        umbral: 2.6,
        mun: true,
        dep: true,
        explicacion: 'Indica la proporción de niños y niñas menores de 5 años que padecen de desnutrición aguda.',
        definicion:
          'Indica la proporción de nacidos vivos a término (37 semanas o más) que nacieron con peso inferior a 2.499 gramos en un momento y territorio específicos, con respecto al total de nacidos vivos en el mismo periodo y lugar.',
        metodologia:
          'Se desconoce, metodología propia del Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE).',
        unidad: 'Por 100 (%)',
        fuente_numerador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE',
        fuente_denominador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE',
        desagregacion: 'Municipal',
        contexto:
          'El bajo peso al nacer es un serio problema de salud pública ya que expresa las condiciones de salud durante la gestación. Se asocia a complicaciones durante los primeros meses de vida, por ejemplo, mortalidad, deficiencias en el desarrollo cognitivo, e incluso puede aumentar el riesgo de padecer enfermedades no transmisibles como la diabetes durante la adultez.',
        interpretacion:
          'Un valor de 2% indica que 2 de cada 100 nacidos vivos a término tienen bajo peso al nacer en un momento y territorio específicos. Más Información: hhttps://apps.who.int/iris/bitstream/handle/10665/255733/WHO_NMH_NHD_14.5_spa.pdf',
      },
    ],
  },
  {
    nombre: 'Educación inicial',
    imagen: 'ya2',
    ruta: 'educacion-inicial',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Niños y niñas menores de 5 años por tipo de establecimiento al que asisten',
        ruta: 'menores-establecimiento',
        archivo: 'ya2-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Cobertura bruta Transición',
        ruta: 'cobertura-transicion',
        archivo: 'ya2-5',
        mun: false,
        dep: true,
        umbral: 85.9,
        explicacion:
          'Indica la proporción de estudiantes que cursan preescolar y asisten a instituciones públicas oficiales.',
        definicion:
          ' La tasa de cobertura bruta mide la relación porcentual entre el número total de estudiantes matriculados (independientemente de la edad que tengan) sobre el total de la población en edad teórica para cursar el nivel educativo, que para el caso de educación preescolar corresponde al rango entre 3 y 5 años de edad.',
        metodologia:
          'La tasa de cobertura bruta mide la relación porcentual entre el número total de estudiantes matriculados (independientemente de la edad que tengan) sobre el total de la población en edad teórica para cursar el nivel educativo, que para el caso de educación preescolar corresponde al rango entre 3 y 5 años de edad.',
        unidad: 'Por 100 (%)',
        fuente_numerador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        fuente_denominador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        desagregacion: 'Municipal',
        contexto:
          'Las tasas de cobertura permiten medir la capacidad del sistema educativo para atender la demanda. No existe un consenso sobre la proporción de estudiantes que asistirn a una institución educativa en particular, ya que esto se acota al contexto en términos de infraestructura y capacidad institucional con la que cuenta cada país.',
        interpretacion:
          'Un valor de 97% indica que 97 de cada 100 estudiantes que cursan en preescolar asisten a un establecimiento educativo oficial en un momento y territorio específicos. Más Información: https://www.dane.gov.co/files/investigaciones/boletines/educacion/formulario-C600-EDUC-2022.pdf',
      },
      {
        nombre: 'Estudiantes preescolar por tipo de establecimiento',
        ruta: 'preescolar',
        archivo: 'ya2-6',
        mun: false,
        dep: true,
        explicacion:
          'Indica la proporción de estudiantes que cursan preescolar y asisten a instituciones públicas oficiales.',
        definicion:
          ' La tasa de cobertura bruta mide la relación porcentual entre el número total de estudiantes matriculados (independientemente de la edad que tengan) sobre el total de la población en edad teórica para cursar el nivel educativo, que para el caso de educación preescolar corresponde al rango entre 3 y 5 años de edad.',
        metodologia: 'Ministerio de Educación Nacional (MEN) - SIMAT.',
        unidad: 'Por 100 (%)',
        fuente_numerador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        fuente_denominador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        desagregacion: 'Municipal',
        contexto:
          'Las tasas de cobertura permiten medir la capacidad del sistema educativo para atender la demanda. No existe un consenso sobre la proporción de estudiantes que asistirn a una institución educativa en particular, ya que esto se acota al contexto en términos de infraestructura y capacidad institucional con la que cuenta cada país.',
        interpretacion:
          'Un valor de 97% indica que 97 de cada 100 estudiantes que cursan en preescolar asisten a un establecimiento educativo oficial en un momento y territorio específicos. Más Información: https://www.dane.gov.co/files/investigaciones/boletines/educacion/formulario-C600-EDUC-2022.pdf',
      },
      {
        nombre: 'Estudiantes primaria por tipo de establecimiento',
        ruta: 'primaria',
        archivo: 'ya2-7',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Hostigamiento a la población civil',
        ruta: 'hostigamiento',
        archivo: 'ya2-8',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Número de incidentes con artefactos explosivos',
        ruta: 'explosivos',
        archivo: 'ya2-9',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Educación preescolar, básica y media',
    imagen: 'ya3',
    ruta: 'educacion-preescolar-a-media',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Tasa de cobertura bruta media',
        ruta: 'cobertura-media',
        archivo: 'ya3-1',
        umbral: 83.6,
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: 'Ministerio de Educación Nacional (MEN) - SIMAT.',
        unidad: 'Por 100 (%)',
        fuente_numerador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        fuente_denominador:
          'Centro de Estudios sobre Desarrollo Económico de la Facultad de Economía de la Universidad de los Andes (CEDE) con base a la C600-DANE.',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Resultados Pruebas Saber 11 matemáticas',
        ruta: 'saber11-matematicas',
        archivo: 'ya3-2',
        umbral: 71,
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Resultados Pruebas Saber 11 español',
        ruta: 'saber11-espanol',
        archivo: 'ya3-3',
        umbral: 71,
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Tasa de deserción',
        ruta: 'desercion',
        archivo: 'ya3-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Tasa de repitencia',
        ruta: 'repitencia',
        archivo: 'ya3-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Tasa de cobertura bruta Primaria',
        ruta: 'cobertura-primaria',
        archivo: 'ya3-6',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Ambiente sano',
    imagen: 'ya4',
    ruta: 'ambiente-sano',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Tasa de mortalidad por Enfermedad Diarreica Aguda (EDA) en menores de 5 años',
        ruta: 'mortalidad-eda',
        archivo: 'ya4-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Tasa de mortalidad por Infección Respiratoria Aguda (IRA) en menores de 5 años',
        ruta: 'mortalidad-ira',
        archivo: 'ya4-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Porcentaje real de acceso a agua potable',
        ruta: 'agua-potable',
        archivo: 'ya4-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Calidad de aire',
        ruta: 'calidad-aire',
        archivo: 'ya4-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Juego',
    imagen: 'ya5',
    ruta: 'juego',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Por definir 1',
        ruta: 'por-definir',
        archivo: 'ya5-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 2',
        ruta: 'por-definir',
        archivo: 'ya5-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 3',
        ruta: 'por-definir',
        archivo: 'ya5-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 4',
        ruta: 'por-definir',
        archivo: 'ya5-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 5',
        ruta: 'por-definir',
        archivo: 'ya5-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Participación',
    imagen: 'ya6',
    ruta: 'participacion',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Por definir 1',
        ruta: 'por-definir',
        archivo: 'ya6-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 2',
        ruta: 'por-definir',
        archivo: 'ya6-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 3',
        ruta: 'por-definir',
        archivo: 'ya6-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 4',
        ruta: 'por-definir',
        archivo: 'ya6-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 5',
        ruta: 'por-definir',
        archivo: 'ya6-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Fortalecimiento Familiar del cuidado y la crianza de la niñez',
    imagen: 'ya7',
    ruta: 'fortalecimiento-familiar',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Por definir 1',
        ruta: 'por-definir',
        archivo: 'ya7-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 2',
        ruta: 'por-definir',
        archivo: 'ya7-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 3',
        ruta: 'por-definir',
        archivo: 'ya7-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 4',
        ruta: 'por-definir',
        archivo: 'ya7-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Por definir 5',
        ruta: 'por-definir',
        archivo: 'ya7-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Protección frente a cualquier tipo de violencia',
    imagen: 'ya8',
    ruta: 'proteccion-violencia',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Proporción de jóvenes que declaran haber experimentado violencia física en los últimos 12 meses',
        ruta: 'violencia-fisica',
        archivo: 'ya8-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre:
          'Número de procesos administrativos de reestablecimientos de derechos por el consumo de sustancias psicoactivas',
        ruta: 'consumo-sustancias',
        archivo: 'ya8-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Número de menores de edad que participaron en la comisión de un delito',
        ruta: 'menores-delito',
        archivo: 'ya8-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre:
      'Adolescentes con justicia restaurativa y pedagógica (sistema de responsabilidad penal para adolescentes - SRPA)',
    imagen: 'ya9',
    ruta: 'adolescentes-srpa',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Porcentaje de adolescentes que ingresan más de una vez al SRPA por presunta comisión de un delito',
        ruta: 'adolescentes-reincidencia',
        archivo: 'ya9-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Tiempo promedio que dura un adolescente o jóven en medida de internamiento preventivo',
        ruta: 'tiempo-promedio',
        archivo: 'ya9-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Número de casos abordados/finalizados en los Programas de Justicia Restaurativa del país',
        ruta: 'casos-justicia',
        archivo: 'ya9-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre:
          'Porcentaje de adolescentes y/o jóvenes en Centros de Atención Especializada y Centros de Internamiento Preventivo con acceso al sistema educativo',
        ruta: 'adolescentes-cae-cip',
        archivo: 'ya9-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre:
          'Porcentaje de jóvenes del SRPA que participan en algún programa para la vinculación laboral (por ejemplo: Número de jóvenes con vinculación laboral por medio del proyecto sueños)',
        ruta: 'vinculacion-laboral',
        archivo: 'ya9-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
  {
    nombre: 'Cultura de paz, reconciliación y convivencia',
    imagen: 'ya10',
    ruta: 'paz-reconciliacion',
    definicion:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam reprehenderit autem illum optio repudiandae enim consectetur alias facere praesentium maiores repellendus, soluta asperiores itaque sit omnis quasi sed in provident.',
    indicadores: [
      {
        nombre: 'Vinculación de Niños, Niñas y Adolescentes a actividades relacionadas con grupos',
        ruta: 'vinculacion-grupos',
        archivo: 'ya10-1',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Ataque a escuelas por grupos al margen de la ley',
        ruta: 'ataque-escuelas',
        archivo: 'ya10-2',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Delitos contra la libertad y la integridad sexual en el desarrollo del conflicto',
        ruta: 'delitos-libertad-sexual',
        archivo: 'ya10-3',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Bajo logro educativo (porcentaje de niños que se encuentran cursando en extra edad)',
        ruta: 'bajo-logro',
        archivo: 'ya10-4',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
      {
        nombre: 'Maltrato Físico (número de ataques a menores de edad por parte de un cuidador, familiar o padre)',
        ruta: 'maltrato-fisico',
        archivo: 'ya10-5',
        mun: false,
        dep: false,
        explicacion: '',
        definicion: '',
        metodologia: '',
        unidad: '',
        fuente_numerador: '',
        fuente_denominador: '',
        desagregacion: '',
        contexto: '',
        interpretacion: '',
      },
    ],
  },
];

export default datos;
