import type { DatosYa } from '@/tipos';

export const ya10: DatosYa = {
  nombre: 'Cultura de paz, reconciliación y convivencia',
  imagen: 'ya10',
  ruta: 'paz-reconciliacion',
  definicion:
    'Es crucial que los 15.4 millones de menores en Colombia participen en la construcción de una cultura de paz tras el conflicto armado. Reconociendo sus experiencias y dándoles voz activa en el diseño de acciones para la reconciliación, la niñez desempeña un papel esencial. Los gobiernos locales, especialmente en los 170 municipios afectados por el conflicto, deben proporcionarles espacio, priorizando la restitución de derechos y el interés superior de la niñez según normativas nacionales e internacionales.',
  hay_datos: true,
  indicadores: [
    {
      nombre: 'Delitos contra la libertad y la integridad sexual en el desarrollo del conflicto',
      ruta: 'delito-sexual-conflicto',
      archivo: 'ya10-1',
      hay_datos: true,
      explicacion_umbral: 'Por definir',
      umbral: 0,
      explicacion: 'Por definir',
      definicion:
        'Indica el número de menores de edad que fueron víctimas de un delito en contra de su libertad e integridad sexual.',
      metodologia: 'Número de menores de edad que fueron reclutados por una estructural criminal.',
      unidad: 'Conteo',
      fuente_numerador: 'Panel CEDE - Registro Único de Víctimas',
      fuente_denominador: 'Panel CEDE - Registro Único de Víctimas',
      desagregacion: 'Municipal',
      contexto: 'Por definir',
      interpretacion: 'Por definir',
    },
    {
      nombre: 'Delitos contra la libertad y la integridad sexual en el desarrollo del conflicto',
      ruta: 'delitos-libertad-sexual',
      archivo: 'ya10-3',
      hay_datos: true,
      explicacion_umbral: 'Por definir',
      explicacion: 'Por definir',
      definicion: 'Por definir',
      metodologia: 'Por definir',
      unidad: 'Por definir',
      fuente_numerador: 'Por definir',
      fuente_denominador: 'Por definir',
      desagregacion: 'Municipal',
      contexto: 'Por definir',
      interpretacion: 'Por definir',
    },
    {
      nombre: 'Maltrato Físico (número de ataques a menores de edad por parte de un cuidador, familiar o padre)',
      ruta: 'maltrato-fisico',
      archivo: 'ya10-5',
      hay_datos: true,
      explicacion_umbral: 'Por definir',
      explicacion: 'Por definir',
      definicion: 'Por definir',
      metodologia: 'Por definir',
      unidad: 'Por definir',
      fuente_numerador: 'Por definir',
      fuente_denominador: 'Por definir',
      desagregacion: 'Municipal',
      contexto: 'Por definir',
      interpretacion: 'Por definir',
    },
    {
      nombre: 'Reclutamiento',
      ruta: 'reclutamiento',
      archivo: 'ya10-2',
      hay_datos: true,
      umbral: 1,
      explicacion: 'Por definir',
      definicion: 'Por definir',
      metodologia: 'Por definir',
      unidad: 'Por definir',
      fuente_numerador: 'Por definir',
      fuente_denominador: 'Por definir',
      desagregacion: 'Municipal',
      contexto: 'Por definir',
      interpretacion: 'Por definir',
    },
  ],
};
