import type { DatosYa } from '@/tipos';

export const ya6: DatosYa = {
  nombre: 'Participación',
  imagen: 'ya6',
  ruta: 'participacion',
  definicion:
    'Es vital reconocer el derecho de la niñez a participar y ser escuchada en decisiones que les afectan, respaldado por normativas como la Declaración Universal de Derechos Humanos. Niñas, niños y adolescentes tienen igualdad de posibilidades y derechos que los adultos para participar y ser escuchados, según diversas normativas. Este derecho no es solo un gesto de buena voluntad, sino el reconocimiento de su capacidad de agencia y formación ciudadana. Sin embargo, la baja priorización y falta de recursos en algunas regiones obstaculizan la efectividad de este derecho, según el Plan Nacional de Desarrollo 2018-2022.',
  hay_datos: false,
  indicadores: [
    {
      nombre: 'Por definir 1',
      ruta: 'por-definir',
      archivo: 'ya6-1',
      hay_datos: false,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: 'Municipal',
      contexto: '',
      interpretacion: '',
    },
    {
      nombre: 'Por definir 2',
      ruta: 'por-definir',
      archivo: 'ya6-2',
      hay_datos: true,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: 'Municipal',
      contexto: '',
      interpretacion: '',
    },
    {
      nombre: 'Por definir 3',
      ruta: 'por-definir',
      archivo: 'ya6-3',
      hay_datos: false,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: 'Municipal',
      contexto: '',
      interpretacion: '',
    },
    {
      nombre: 'Por definir 4',
      ruta: 'por-definir',
      archivo: 'ya6-4',
      hay_datos: false,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: 'Municipal',
      contexto: '',
      interpretacion: '',
    },
    {
      nombre: 'Por definir 5',
      ruta: 'por-definir',
      archivo: 'ya6-5',
      hay_datos: false,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: 'Municipal',
      contexto: '',
      interpretacion: '',
    },
  ],
};
