import type { DatosYa } from '@/tipos';

export const ya9: DatosYa = {
  nombre:
    'Adolescentes con justicia restaurativa y pedagógica (Sistema de Responsabilidad Penal para Adolescentes - SRPA)',
  imagen: 'ya9',
  ruta: 'justicia-restaurativa',
  definicion: '',
  hay_datos: false,
  indicadores: [
    {
      nombre: '...',
      ruta: 'slug',
      hay_datos: false,
      explicacion_umbral: '',
      umbral: 0,
      explicacion: '',
      definicion: '',
      metodologia: '',
      unidad: '',
      fuente_numerador: '',
      fuente_denominador: '',
      desagregacion: '',
      contexto: '',
      interpretacion: '',
    },
    // {
    //   nombre: 'Delitos contra la libertad y la integridad sexual en el desarrollo del conflicto',
    //   ruta: 'delitos-libertad-sexual',
    //   archivo: 'ya10-3',
    //   hay_datos: false,
    //   explicacion_umbral: 'Por definir',
    //   explicacion: 'Por definir',
    //   definicion: 'Por definir',
    //   metodologia: 'Por definir',
    //   unidad: 'Por definir',
    //   fuente_numerador: 'Por definir',
    //   fuente_denominador: 'Por definir',
    //   desagregacion: 'Municipal',
    //   contexto: 'Por definir',
    //   interpretacion: 'Por definir',
    // },
    // {
    //   nombre: 'Maltrato Físico (número de ataques a menores de edad por parte de un cuidador, familiar o padre)',
    //   ruta: 'maltrato-fisico',
    //   archivo: 'ya10-5',
    //   hay_datos: false,
    //   explicacion_umbral: 'Por definir',
    //   explicacion: 'Por definir',
    //   definicion: 'Por definir',
    //   metodologia: 'Por definir',
    //   unidad: 'Por definir',
    //   fuente_numerador: 'Por definir',
    //   fuente_denominador: 'Por definir',
    //   desagregacion: 'Municipal',
    //   contexto: 'Por definir',
    //   interpretacion: 'Por definir',
    // },
  ],
};
